import assert from 'node:assert/strict';

import { createFollowing, sentenceSpokenAt } from '../src/core/following.js';
import { cutIntoSentences } from '../src/core/transcript.js';
import { fromTheUploader, oldAutoGenerated, recentAutoGenerated, test } from './real-captions.js';
import { standInPlayer } from './stand-in-player.js';

/** A word-timed Transcript saying `text`, a word every 0.5 s from 10 s. */
const wordTimed = (text) => ({
  language: 'en',
  source: 'auto-generated',
  timing: 'word',
  pieces: text.split(' ').map((word, i) => ({ text: word, start: 10 + i * 0.5 })),
});

test('on a word-timed Transcript the sentence being spoken is the one whose words are being said', () => {
  // "Good" 10 s, "morning." 10.5 s, "How" 11 s, "are" 11.5 s, "you?" 12 s, "Fine." 12.5 s
  const { sentences } = cutIntoSentences(wordTimed('Good morning. How are you? Fine.'));

  assert.equal(sentences[sentenceSpokenAt(sentences, 10.7)].text, 'Good morning.');
  assert.equal(sentences[sentenceSpokenAt(sentences, 11.9)].text, 'How are you?');
});

test('a sentence is the one being spoken from the moment it starts, and no sooner', () => {
  const { sentences } = cutIntoSentences(wordTimed('Good morning. How are you? Fine.'));

  assert.equal(sentenceSpokenAt(sentences, 10.999), 0);
  assert.equal(sentenceSpokenAt(sentences, 11), 1);
});

test('before the first sentence starts, none is being spoken', () => {
  const { sentences } = cutIntoSentences(wordTimed('Good morning. How are you? Fine.'));

  assert.equal(sentenceSpokenAt(sentences, 0), -1);
  assert.equal(sentenceSpokenAt(sentences, 9.999), -1);
  assert.equal(sentenceSpokenAt([], 12), -1);
});

test('a sentence stays the one being spoken through the silence after it, and the last one to the end of the video', () => {
  const transcript = wordTimed('Good morning. How are you? Fine.');
  transcript.pieces[2].start = 40; // a long silence before "How"
  transcript.pieces[3].start = 40.5;
  transcript.pieces[4].start = 41;
  transcript.pieces[5].start = 41.5;
  const { sentences } = cutIntoSentences(transcript);

  assert.equal(sentences[sentenceSpokenAt(sentences, 39)].text, 'Good morning.');
  assert.equal(sentences[sentenceSpokenAt(sentences, 3600)].text, 'Fine.');
});

test('on a cue-timed Transcript, sentences that share a cue are told apart by how far along its text each one stands', () => {
  // One cue of 26 characters, from 10 s to 14 s. "How" stands 14 characters in: 10 + 4 × 14/26 = 12.154 s.
  const { sentences } = cutIntoSentences({
    language: 'en',
    source: 'uploader',
    timing: 'cue',
    pieces: [
      { text: 'Good morning. How are you?', start: 10, end: 14 },
      { text: 'Fine.', start: 14.5, end: 15.5 },
    ],
  });

  assert.equal(sentences[sentenceSpokenAt(sentences, 10)].text, 'Good morning.');
  assert.equal(sentences[sentenceSpokenAt(sentences, 12.1)].text, 'Good morning.');
  assert.equal(sentences[sentenceSpokenAt(sentences, 12.2)].text, 'How are you?');
  assert.equal(sentences[sentenceSpokenAt(sentences, 14.2)].text, 'How are you?');
  assert.equal(sentences[sentenceSpokenAt(sentences, 14.5)].text, 'Fine.');
});

// Cues that overlap in time: one comes on while the one before it is still up, as a second speaker's
// does, or a caption timed a little early. None of the three real sets has any.

/** A cue-timed Transcript of the uploader's, each cue a start, an end and its text. */
const cues = (...said) => ({ language: 'en', source: 'uploader', timing: 'cue', pieces: said.map(([start, end, text]) => ({ start, end, text })) });

test('where a cue comes on before the one before it has ended, each line is still the one being spoken for a time, in the order the lines come', () => {
  // "Fine." comes on at 11 s, and the cue before it stays up until 14 s.
  const { sentences } = cutIntoSentences(cues([10, 14, 'Good morning. How are you?'], [11, 13, 'Fine.'], [14, 16, 'And you?']));
  const spokenAt = (seconds) => sentences[sentenceSpokenAt(sentences, seconds)]?.text ?? null;

  assert.equal(spokenAt(10), 'Good morning.');
  assert.equal(spokenAt(10.9), 'How are you?');
  assert.equal(spokenAt(11), 'Fine.');
  assert.equal(spokenAt(13.9), 'Fine.');
  assert.equal(spokenAt(14), 'And you?');
});

test('whatever way cues overlap, every sentence is the one being spoken at its own start', () => {
  const overlapping = {
    'a cue comes on before the one before it has ended': cues([10, 14, 'Good morning. How are you?'], [11, 13, 'Fine.'], [14, 16, 'And you?'], [16, 18, 'Very well.']),
    'two cues come on together': cues([10, 12, 'Good morning.'], [10, 12, 'How are you?'], [12, 14, 'Fine.']),
    'a long cue stays up while two short ones come and go': cues([10, 20, 'I think we should go now. Do you agree?'], [11, 12, 'Yes.'], [13, 14, 'Of course.'], [20, 22, 'Good.']),
    'a cue is listed after one that starts later': cues([10, 12, 'Good morning. How are you?'], [14, 16, 'And you?'], [12, 14, 'Fine. Thank you.'], [16, 18, 'Very well.']),
  };

  for (const [how, transcript] of Object.entries(overlapping)) {
    const { sentences } = cutIntoSentences(transcript);

    assert.deepEqual(sentences.map((sentence) => sentenceSpokenAt(sentences, sentence.start)), sentences.map((_, place) => place), how);
  }
});

// The three real sets of captions. The times and words below are read off the captions themselves.
const spokenIn = (transcript) => {
  const { sentences } = cutIntoSentences(transcript);
  return { sentences, at: (seconds) => sentences[sentenceSpokenAt(sentences, seconds)]?.text ?? null };
};

test('real word-timed captions: the sentence being spoken at a time', () => {
  const dinner = spokenIn(recentAutoGenerated());

  assert.equal(dinner.at(0.5), null); // the applause starts at 0.654 s
  assert.equal(dinner.at(0.7), '[applause]');
  assert.equal(dinner.at(4.5), 'Please remain seated.'); // 4 s to 5.16 s
  assert.equal(dinner.at(5.16), "That's not necessary.");
  assert.equal(dinner.at(371), 'Duck Dynasty!'); // 370.12 s to 372.12 s
  assert.equal(dinner.at(1700), 'Thank you very much.'); // the last, from 1635.4 s
});

test('real cue-timed captions: the sentence being spoken at a time, two of them inside one cue', () => {
  const talk = spokenIn(fromTheUploader());

  assert.equal(talk.at(27), null); // the first cue starts at 27.103 s
  // One cue, 27.103 s to 29.678 s: "Good morning. How are you?"
  assert.equal(talk.at(28), 'Good morning.');
  assert.equal(talk.at(29), 'How are you?');
  // The next, 29.702 s to 31.105 s: "(Audience) Good."
  assert.equal(talk.at(30), '(Audience)');
  assert.equal(talk.at(31), 'Good.');
  assert.equal(talk.at(34), "I've been blown away by the whole thing."); // a cue of its own, from 33.408 s
});

test('real captions with no punctuation: the sentence being spoken at a time', () => {
  const talk = spokenIn(oldAutoGenerated());

  assert.equal(talk.at(20), '[Music]'); // from 6.26 s, and nothing else until 26.56 s
  assert.equal(talk.at(27), 'good morning');
  assert.equal(talk.at(29), 'how are you'); // 28.4 s to 30.72 s
});

test('in all three real sets, every sentence is the one being spoken at its own start', () => {
  for (const transcript of [recentAutoGenerated(), fromTheUploader(), oldAutoGenerated()]) {
    const { sentences } = cutIntoSentences(transcript);

    assert.deepEqual(sentences.map((sentence) => sentenceSpokenAt(sentences, sentence.start)), sentences.map((_, place) => place));
  }
});

// ------------------------------------------------------------ following

const talk = { id: 'youtube:iG9CE55wbtY', title: 'How to read a transcript', channel: 'Leo Reads' };

/** A Transcript as the panel has it on show once it is ready (see src/core/panel.js). */
const onShow = (transcript) => ({ status: 'ready', line: null, ...transcript, ...cutIntoSentences(transcript) });

// "Good" 10 s, "morning." 10.5 s, "How" 11 s, "are" 11.5 s, "you?" 12 s, "Fine." 12.5 s
const greeting = () => onShow(wordTimed('Good morning. How are you? Fine.'));

/** The following on a stand-in player, with a Transcript on show, and everything it has shown, latest last. */
function followingOn(transcript, { at = 0 } = {}) {
  const shown = [];
  const player = standInPlayer({ video: talk, currentTime: at });
  const following = createFollowing({ player, show: (state) => shown.push(state) });
  following.transcriptShown(transcript);
  return { following, player, shown };
}
/** Lets everything already under way finish. */
const settled = () => new Promise((resolve) => setImmediate(resolve));

test('while the video plays, the panel is shown the sentence being spoken, and that it is following', async () => {
  const { following, player, shown } = followingOn(greeting());

  player.playTo(10.7);
  await following.catchUp();
  assert.deepEqual(shown.at(-1), { spoken: 0, following: true });

  player.playTo(11.2);
  await following.catchUp();
  assert.deepEqual(shown.at(-1), { spoken: 1, following: true });
});

test('the panel is shown something only when the sentence being spoken is another one, so a paused video shows nothing new', async () => {
  const { following, player, shown } = followingOn(greeting(), { at: 11.2 });
  await following.catchUp();
  const before = shown.length;

  // Still inside "How are you?", and then paused there.
  player.playTo(11.9);
  await following.catchUp();
  await following.catchUp();
  await following.catchUp();

  assert.equal(shown.length, before);
  assert.deepEqual(shown.at(-1), { spoken: 1, following: true });
});

test('a seek in the player, forwards or back, shows at the next catch-up', async () => {
  const { following, player, shown } = followingOn(greeting(), { at: 10.2 });
  await following.catchUp();

  player.playTo(12.6);
  await following.catchUp();
  assert.deepEqual(shown.at(-1), { spoken: 2, following: true });

  player.playTo(10.1);
  await following.catchUp();
  assert.deepEqual(shown.at(-1), { spoken: 0, following: true });

  // Back to before anything is said.
  player.playTo(3);
  await following.catchUp();
  assert.deepEqual(shown.at(-1), { spoken: -1, following: true });
});

test('scrolling by hand stops the following, and the sentence being spoken is still shown as the video plays on', async () => {
  const { following, player, shown } = followingOn(greeting(), { at: 10.2 });
  await following.catchUp();

  following.scrolledByHand();
  assert.deepEqual(shown.at(-1), { spoken: 0, following: false });

  player.playTo(11.2);
  await following.catchUp();
  assert.deepEqual(shown.at(-1), { spoken: 1, following: false });
});

test('"back to now" resumes the following', async () => {
  const { following, player, shown } = followingOn(greeting(), { at: 10.2 });
  await following.catchUp();
  following.scrolledByHand();
  player.playTo(12.6);
  await following.catchUp();

  following.backToNow();

  assert.deepEqual(shown.at(-1), { spoken: 2, following: true });
});

test('a scroll is many events and "back to now" may be clicked twice: the panel is shown each change once', async () => {
  const { following, shown } = followingOn(greeting(), { at: 10.2 });
  await following.catchUp();
  const before = shown.length;

  following.scrolledByHand();
  following.scrolledByHand();
  following.scrolledByHand();
  assert.deepEqual(shown.slice(before), [{ spoken: 0, following: false }]);

  following.backToNow();
  following.backToNow();
  assert.deepEqual(shown.slice(before), [{ spoken: 0, following: false }, { spoken: 0, following: true }]);
});

test('jumping to a sentence moves the video to the start of that sentence, and shows it as the one being spoken', async () => {
  const { following, player, shown } = followingOn(greeting(), { at: 10.2 });
  await following.catchUp();

  await following.jumpTo(2); // "Fine.", which starts at 12.5 s

  assert.equal(await player.currentTime(), 12.5);
  assert.deepEqual(shown.at(-1), { spoken: 2, following: true });
});

test('a jump made after scrolling away resumes the following, shown in one go with the sentence jumped to', async () => {
  const { following, player, shown } = followingOn(greeting(), { at: 12.6 });
  await following.catchUp();
  following.scrolledByHand();
  const before = shown.length;

  await following.jumpTo(0);

  assert.equal(await player.currentTime(), 10);
  assert.deepEqual(shown.slice(before), [{ spoken: 0, following: true }]);
});

test('on real cue-timed captions, a jump to a sentence that starts inside a cue goes to its place in the cue, not to the start of the cue', async () => {
  // One cue, 27.103 s to 29.678 s: "Good morning. How are you?"
  const { following, player, shown } = followingOn(onShow(fromTheUploader()), { at: 400 });
  await following.catchUp();

  await following.jumpTo(1);

  assert.equal(await player.currentTime(), 28.49);
  assert.deepEqual(shown.at(-1), { spoken: 1, following: true });
});

test('while an advert plays the panel holds still, and carries on when the advert is over', async () => {
  const { following, player, shown } = followingOn(greeting(), { at: 11.2 });
  await following.catchUp();
  const before = shown.length;

  player.advert(true);
  await following.catchUp();
  await following.catchUp();

  assert.equal(shown.length, before);
  assert.deepEqual(shown.at(-1), { spoken: 1, following: true });

  player.advert(false);
  player.playTo(12.6);
  await following.catchUp();

  assert.deepEqual(shown.at(-1), { spoken: 2, following: true });
});

test('a jump asked for while an advert plays does nothing: the video stays, and so does what the panel shows', async () => {
  const { following, player, shown } = followingOn(greeting(), { at: 12.6 });
  await following.catchUp();
  following.scrolledByHand();
  const before = shown.length;

  player.advert(true);
  await following.jumpTo(0);

  assert.equal(shown.length, before);
  assert.deepEqual(shown.at(-1), { spoken: 2, following: false });

  player.advert(false);
  assert.equal(await player.currentTime(), 12.6);
});

test('when another Transcript comes on show the following starts again: nothing spoken yet, and following', async () => {
  const { following, shown } = followingOn(greeting(), { at: 12.6 });
  await following.catchUp();
  following.scrolledByHand();
  assert.deepEqual(shown.at(-1), { spoken: 2, following: false });

  // "This" 10 s, "is" 10.5 s, "the" 11 s, "lecture." 11.5 s
  following.transcriptShown(onShow(wordTimed('This is the lecture.')));
  assert.deepEqual(shown.at(-1), { spoken: -1, following: true });

  await following.catchUp();
  assert.deepEqual(shown.at(-1), { spoken: 0, following: true });
});

test('being told again of the Transcript already on show changes nothing', async () => {
  // The panel shows everything again whenever the video's title or anything else changes.
  const transcript = greeting();
  const { following, shown } = followingOn(transcript, { at: 12.6 });
  await following.catchUp();
  following.scrolledByHand();
  const before = shown.length;

  following.transcriptShown(transcript);
  // The same sentences in another object, as when something else about the Transcript on show has changed.
  following.transcriptShown({ ...transcript });

  assert.equal(shown.length, before);
  assert.deepEqual(shown.at(-1), { spoken: 2, following: false });
});

test('with no Transcript on show there is nothing to follow: no sentence is spoken, the player is not asked, and nothing the user does changes that', async () => {
  const waiting = { status: 'getting', line: 'Getting the transcript…' };
  const none = { status: 'none', line: 'This video has no transcript.' };
  const failed = { status: 'failed', line: 'The transcript could not be fetched.', reason: 'The player gave no token in 90 s.' };

  for (const instead of [waiting, none, failed, null]) {
    const { following, player, shown } = followingOn(greeting(), { at: 11.2 });
    await following.catchUp();
    following.scrolledByHand();
    let asked = 0;
    const currentTime = player.currentTime;
    player.currentTime = () => {
      asked += 1;
      return currentTime();
    };

    following.transcriptShown(instead);
    assert.deepEqual(shown.at(-1), { spoken: -1, following: true });
    const before = shown.length;

    await following.catchUp();
    following.scrolledByHand();
    following.backToNow();
    await following.jumpTo(1);

    assert.equal(shown.length, before);
    assert.equal(asked, 0);
    assert.equal(await currentTime(), 11.2);
  }
});

test('a time the player answers after the tab has moved to another video is not shown against the Transcript that came instead', async () => {
  const { following, player, shown } = followingOn(greeting(), { at: 10.2 });
  await following.catchUp();
  // The player is slow to answer: the tab moves on while the question is out.
  const answers = [];
  player.currentTime = () => new Promise((answer) => answers.push(answer));

  const catchingUp = following.catchUp();
  following.transcriptShown({ status: 'getting', line: 'Getting the transcript…' });
  answers[0](12.6);
  await catchingUp;
  assert.deepEqual(shown.at(-1), { spoken: -1, following: true });

  // The same for a jump: asked for on one Transcript, answered when another is on show.
  following.transcriptShown(greeting());
  const jumping = following.jumpTo(2);
  following.transcriptShown(onShow(wordTimed('This is the lecture. It is long.')));
  await settled();
  answers.forEach((answer) => answer(12.6));
  await jumping;
  assert.deepEqual(shown.at(-1), { spoken: -1, following: true });
});

// A Note shows its time, and a click on that time jumps there: to a time, not to a sentence.
test("jumping to a time, as a click on a Note's time does, moves the video there, shows the sentence spoken then and resumes the following", async () => {
  const { following, player, shown } = followingOn(greeting(), { at: 12.6 });
  await following.catchUp();
  following.scrolledByHand();
  const before = shown.length;

  await following.jumpToTime(11.7); // while "How are you?" is being said, from 11 s

  assert.equal(await player.currentTime(), 11.7);
  assert.deepEqual(shown.slice(before), [{ spoken: 1, following: true }]);
});

test('with no Transcript on show a jump to a time still moves the video, and there is nothing to show of it', async () => {
  const { following, player, shown } = followingOn({ status: 'none', line: 'This video has no transcript.' }, { at: 11.2 });
  const before = shown.length;

  await following.jumpToTime(30);

  assert.equal(await player.currentTime(), 30);
  assert.equal(shown.length, before);
});

test('a jump to a time asked for while an advert plays does nothing either', async () => {
  const { following, player, shown } = followingOn(greeting(), { at: 10.2 });
  await following.catchUp();
  following.scrolledByHand();
  const before = shown.length;
  player.advert(true);

  await following.jumpToTime(12.6);

  player.advert(false);
  assert.equal(await player.currentTime(), 10.2);
  assert.equal(shown.length, before);
});
