// Highlights, through the panel: selecting words makes one, the store keeps
// it, and it shows again when the video is reopened. The store here is a
// stand-in; the real one is the extension's own local storage.

import assert from 'node:assert/strict';

import { highlightOf, highlightsOf, placeHighlight, removeHighlight, saveHighlight } from '../src/core/highlights.js';
import { COLOURS, colourOf } from '../src/core/highlights.js';
import { createPanel } from '../src/core/panel.js';
import { cutIntoSentences } from '../src/core/transcript.js';
import { standInPlayer } from './stand-in-player.js';
import { standInStore } from './stand-in-store.js';
import { fromTheUploader, oldAutoGenerated, recentAutoGenerated, test } from './real-captions.js';

// The two videos the real captions are of. Two of the three sets are the talk's.
const talk = { id: 'youtube:iG9CE55wbtY', title: 'Do schools kill creativity?', channel: 'TED' };
const dinner = { id: 'youtube:rddfPNBNAJs', title: 'Remarks after dinner', channel: 'The Dinner' };

/** A Transcript saying `text`, a word every 0.3 s from 1 s in. */
const saying = (text) => ({
  language: 'en',
  source: 'auto-generated',
  timing: 'word',
  pieces: text.split(' ').map((word, i) => ({ text: word, start: (10 + i * 3) / 10 })),
});

/** Lets everything already under way finish. */
const settled = () => new Promise((resolve) => setImmediate(resolve));

/**
 * A panel open on a video whose Transcript has arrived. `now()` is what it
 * shows. Give it the store of an earlier panel to open the video again.
 * `transcript` is the Transcript of every video, or a function that gives each video's.
 */
async function panelOn(video, transcript, store = standInStore()) {
  const shown = [];
  const player = standInPlayer({ video });
  const fetchTranscript = async (asked) => (typeof transcript === 'function' ? transcript(asked) : transcript);
  const panel = createPanel({ player, fetchTranscript, store, show: (state) => shown.push(state) });
  await panel.refresh();
  await settled();
  return { panel, player, store, shown, now: () => shown.at(-1) };
}

/** Where `phrase` stands among the words on show: its first word's place and its last word's. */
function placesOf({ transcript }, phrase) {
  const wanted = phrase.split(' ');
  const first = transcript.words.findIndex((_, at) => wanted.every((text, i) => transcript.words[at + i]?.text === text));
  assert.ok(first >= 0, `"${phrase}" is in the Transcript`);
  return [first, first + wanted.length - 1];
}
/** Selects `phrase` in the Transcript on show and lets go. */
const select = ({ panel, now }, phrase) => panel.highlight(...placesOf(now(), phrase));

/** The lines on show, each as its text, with every mark between « and », after its colour when the mark names one. */
function lines({ transcript, marks }) {
  const colour = (part) => ('colour' in part ? `${part.colour}:` : '');
  const written = (parts) => parts.map((part) => (part === ' ' ? ' ' : typeof part === 'number' ? transcript.words[part].text : `«${colour(part)}${written(part.parts)}»`)).join('');
  return transcript.sentences.map((sentence, at) => (marks.has(at) ? written(marks.get(at)) : sentence.text));
}

test('selecting words makes a Highlight of exactly those words, shown as a mark in its line', async () => {
  const open = await panelOn(talk, saying("It's been great. I've been blown away by the whole thing."));

  await select(open, 'blown away');

  assert.deepEqual(lines(open.now()), ["It's been great.", "I've been «blown away» by the whole thing."]);
  assert.deepEqual(open.now().highlights.map((highlight) => highlight.words), ['blown away']);
});

test('a selection across several sentences makes one Highlight, with a mark in each line it covers', async () => {
  const open = await panelOn(talk, saying("It's been great. I've been blown away. In fact I'm leaving. Good."));

  await select(open, "great. I've been blown away. In fact");

  assert.deepEqual(lines(open.now()), ["It's been «great.»", "«I've been blown away.»", "«In fact» I'm leaving.", 'Good.']);
  assert.deepEqual(open.now().highlights.map((highlight) => highlight.words), ["great. I've been blown away. In fact"]);
  // One Highlight: every one of those marks is its own.
  const [{ id }] = open.now().highlights;
  const marksIn = (line) => open.now().marks.get(line).filter((part) => typeof part === 'object').map((mark) => mark.highlight);
  assert.deepEqual([marksIn(0), marksIn(1), marksIn(2)], [[id], [id], [id]]);
});

test('a Highlight is saved with its time range, a copy of its words, which Transcript they came from and when it was made, under a format version number', async () => {
  const before = Date.now();
  const open = await panelOn(dinner, recentAutoGenerated());

  // "Please remain seated. That's not necessary." The captions time those
  // words at 4, 4.36, 4.72 and 5.16 s.
  await select(open, 'remain seated.');

  const [saved] = open.now().highlights;
  assert.deepEqual(open.store.everything(), {
    formatVersion: 1,
    // The video's identity is the one thing here that names YouTube.
    'video:youtube:rddfPNBNAJs': {
      title: 'Remarks after dinner',
      channel: 'The Dinner',
      highlights: [
        {
          id: saved.id,
          start: 4.36,
          end: 5.16,
          words: 'remain seated.',
          transcript: { language: 'en', source: 'auto-generated' },
          made: saved.made,
        },
      ],
    },
  });
  assert.match(saved.id, /^\S+$/);
  assert.equal(new Date(saved.made).toISOString(), saved.made, 'the time it was made is written as a date and time');
  assert.ok(Date.parse(saved.made) >= before && Date.parse(saved.made) <= Date.now());
});

test('reopening the video shows the Highlight again, in the same words', async () => {
  const first = await panelOn(dinner, recentAutoGenerated());
  await select(first, 'remain seated.');

  // The tab is closed and the video opened again: another panel, the same store.
  const again = await panelOn(dinner, recentAutoGenerated(), first.store);

  assert.equal(lines(again.now())[4], 'Please «remain seated.»');
  assert.deepEqual(again.now().highlights, first.now().highlights);
});

/** The time range of each Highlight on show. */
const ranges = ({ highlights }) => highlights.map((highlight) => [highlight.words, highlight.start, highlight.end]);

test('on a word-timed Transcript a Highlight runs from its first word to the next word said, and no further than 1.5 s past its last word', async () => {
  const open = await panelOn(dinner, recentAutoGenerated());

  // "That's not necessary." is timed at 5.16, 5.4 and 5.56 s, and nothing is said after it until 7.32 s.
  await select(open, "That's not");
  await select(open, 'not necessary.');

  assert.deepEqual(ranges(open.now()), [
    ["That's not", 5.16, 5.56],
    ['not necessary.', 5.4, 7.06],
  ]);
});

test('a Highlight of the last words of a word-timed Transcript ends 0.8 s after the last word starts', async () => {
  const open = await panelOn(dinner, recentAutoGenerated());
  const words = open.now().transcript.words;

  // The Transcript ends "Thank you very much.", with "much." at 1636 s.
  await open.panel.highlight(words.length - 2, words.length - 1);

  assert.deepEqual(ranges(open.now()), [['very much.', 1635.76, 1636.8]]);
  assert.equal(lines(open.now()).at(-1), 'Thank you «very much.»');
});

test('two words the captions time together are still two words: a Highlight of one does not take the other', async () => {
  const open = await panelOn(talk, oldAutoGenerated());

  // "that was it by the way thank you very much": the captions give "the way"
  // one time, 211.12 s, and "thank" is said at 211.28 s.
  const [by] = placesOf(open.now(), 'by the way thank');
  await open.panel.highlight(by + 1, by + 1);

  assert.deepEqual(ranges(open.now()), [['the', 211.12, 211.28]]);
  assert.ok(lines(open.now()).includes('that was it by «the» way thank you very much'));

  await open.panel.highlight(by + 2, by + 2);

  assert.deepEqual(ranges(open.now()), [['the', 211.12, 211.28], ['way', 211.12, 211.28]]);
  assert.ok(lines(open.now()).includes('that was it by «the» «way» thank you very much'));
});

test('on a cue-timed Transcript the time range widens to the whole cue or cues, and the saved words stay exactly what was selected', async () => {
  const open = await panelOn(talk, fromTheUploader());

  // The cue "I've been blown away by the whole thing." runs from 33.408 to 35.729 s.
  await select(open, 'blown away by the whole thing.');
  // "One is the extraordinary evidence of human creativity" is a cue from
  // 48.997 s, and "in all of the presentations that we've had" is the next, to 55.904 s.
  await select(open, 'evidence of human creativity in all');

  assert.deepEqual(ranges(open.now()), [
    ['blown away by the whole thing.', 33.408, 35.729],
    ['evidence of human creativity in all', 48.997, 55.904],
  ]);
  assert.deepEqual(open.now().highlights[0].transcript, { language: 'en', source: 'uploader' });
  // The mark is on the words selected, not on the whole cue.
  assert.equal(lines(open.now())[5], "I've been «blown away by the whole thing.»");
  assert.equal(
    lines(open.now())[9],
    "One is the extraordinary «evidence of human creativity in all» of the presentations that we've had and in all of the people here; just the variety of it and the range of it."
  );
});

test('a cue that the captions give no length still takes a Highlight, and shows it', async () => {
  const cues = [
    { text: 'Good morning.', start: 1, end: 2 },
    { text: 'How are you?', start: 2, end: 2 },
    { text: 'Good.', start: 3, end: 4 },
  ];
  const open = await panelOn(talk, { language: 'en', source: 'uploader', timing: 'cue', pieces: cues });

  await select(open, 'are you?');

  // It counts as a millisecond long, so that the Highlight has a time range to show in.
  assert.deepEqual(ranges(open.now()), [['are you?', 2, 2.001]]);
  assert.deepEqual(lines(open.now()), ['Good morning.', 'How «are you?»', 'Good.']);
});

test('a Highlight made on the cue-timed Transcript shows on the word-timed one of the same video, on the same words', async () => {
  const first = await panelOn(talk, fromTheUploader());
  await select(first, 'blown away by the whole thing.');

  // The same video, opened again with its auto-generated captions.
  const again = await panelOn(talk, oldAutoGenerated(), first.store);

  // The Highlight's time range is its cue's, 33.408 to 35.729 s. The words
  // these captions time inside it are "i've been blown away by the whole
  // thing in fact", from 33.44 to 35.52 s. The saved words are among them,
  // though here they have no full stop.
  assert.equal(lines(again.now())[4], "it's been i've been «blown away by the whole thing» in fact i'm leaving");
  // What is saved has not changed: the quote still reads as it did when it was marked.
  assert.deepEqual(again.now().highlights, first.now().highlights);
  assert.deepEqual(ranges(again.now()), [['blown away by the whole thing.', 33.408, 35.729]]);
});

test('when the saved words are not in the time range on the Transcript now on show, the whole range is marked', async () => {
  const first = await panelOn(talk, fromTheUploader());
  // One cue, from 46.687 to 48.973 s.
  await select(first, 'which are relevant to what I want to talk about.');

  const again = await panelOn(talk, oldAutoGenerated(), first.store);

  // The auto-generated captions heard "which are rather relevant", and time
  // "which are" before the cue starts. What they time inside it runs from
  // "rather" at 46.719 s to "the" at 48.8 s, and all of that is marked.
  assert.equal(lines(again.now())[7], 'uh which are «rather relevant to what i want to talk about one is the» extraordinary');
  assert.deepEqual(ranges(again.now()), [['which are relevant to what I want to talk about.', 46.687, 48.973]]);
});

test('a Highlight made on the word-timed Transcript shows on the cue-timed one: on its words if they are there, or else on every cue it reaches into', async () => {
  const first = await panelOn(talk, oldAutoGenerated());
  await select(first, 'blown away by the whole thing');
  await select(first, 'rather relevant');
  assert.deepEqual(ranges(first.now()), [
    ['blown away by the whole thing', 33.92, 35.36],
    ['rather relevant', 46.719, 47.44],
  ]);

  const again = await panelOn(talk, fromTheUploader(), first.store);

  assert.equal(lines(again.now())[5], "I've been «blown away by the whole thing.»");
  // The uploader's captions have no "rather", so the cue those two words fall in is marked whole.
  assert.equal(lines(again.now())[8], 'There have been three themes running through the conference, «which are relevant to what I want to talk about.»');
});

test('of two runs of the same words in one cue, the mark is on the one written as the saved words are', async () => {
  const open = await panelOn(talk, fromTheUploader());
  const line = 'One is the extraordinary evidence of human creativity in all of the presentations that we\'ve had and in all of the people here; just the variety of it and the range of it.';
  assert.equal(lines(open.now())[9], line);

  // The cue is "just the variety of it / and the range of it." The second "of it." has the full stop.
  const [, last] = placesOf(open.now(), 'and the range of it.');
  await open.panel.highlight(last - 1, last);

  assert.equal(lines(open.now())[9], line.replace('range of it.', 'range «of it.»'));
});

test('when a cue holds the selected words twice, written alike, the Highlight saves which of them it was, and the mark is on that one', async () => {
  const open = await panelOn(talk, fromTheUploader());

  // The second "the" of the cue "just the variety of it / and the range of it."
  const [and] = placesOf(open.now(), 'and the range of it.');
  await open.panel.highlight(and + 1, and + 1);

  // The cue's time range and the word "the" fit both, so the Highlight also says it is the second: counted from 0.
  assert.deepEqual(ranges(open.now()), [['the', 57.904, 60.555]]);
  assert.equal(open.now().highlights[0].occurrence, 1);
  assert.ok(lines(open.now())[9].endsWith('just the variety of it and «the» range of it.'));

  // And it is on the second when the video is opened again.
  const again = await panelOn(talk, fromTheUploader(), open.store);
  assert.ok(lines(again.now())[9].endsWith('just the variety of it and «the» range of it.'));
});

test('a Highlight of the first of them, or of words its time range holds once, saves nothing more, and one saved without it marks the first', async () => {
  const open = await panelOn(talk, fromTheUploader());

  const [just] = placesOf(open.now(), 'just the variety of it');
  await open.panel.highlight(just + 1, just + 1);
  await select(open, 'blown away by the whole thing.');

  assert.ok(open.now().highlights.every((highlight) => !('occurrence' in highlight)));
  assert.ok(lines(open.now())[9].endsWith('just «the» variety of it and the range of it.'));
});

test("on another Transcript whose time range holds the words fewer times, the Highlight marks the first of them there", async () => {
  const first = await panelOn(talk, fromTheUploader());
  // The second "the" of the cue "just the variety of it / and the range of it.", from 57.904 to 60.555 s.
  const [and] = placesOf(first.now(), 'and the range of it.');
  await first.panel.highlight(and + 1, and + 1);

  const again = await panelOn(talk, oldAutoGenerated(), first.store);

  // The auto-generated captions time "variety of it and the range of it" inside that range: one "the".
  assert.ok(lines(again.now()).some((line) => line.includes('variety of it and «the» range of it')));
});

// A bracketed phrase with a space in it, such as "(more or less)", is one word
// of the Transcript. A Highlight saves its words with one space between them,
// so in what is saved nothing tells that phrase from three words.

/** A cue-timed Transcript of the uploader's, each cue a start, an end and its text. */
const cues = (...said) => ({ language: 'en', source: 'uploader', timing: 'cue', pieces: said.map(([start, end, text]) => ({ start, end, text })) });
/** One cue of two sentences, so that a Highlight's time range, its cue's, holds more than its own sentence. */
const moreOrLess = () => cues([10, 14, 'It went fine (more or less) in the end. We were lucky.'], [14, 16, 'That was all.']);
/** Where the word that reads `text` stands among the words on show, counting from the `nth` of them. */
const placeOf = ({ transcript }, text, nth = 0) => transcript.words.flatMap((word, place) => (word.text === text ? [place] : []))[nth];

test('selecting words that include a bracketed phrase with a space in it marks exactly those words, at once and when the video is reopened', async () => {
  const open = await panelOn(talk, moreOrLess());
  assert.deepEqual(open.now().transcript.words.slice(2, 5).map((word) => word.text), ['fine', '(more or less)', 'in']);

  await open.panel.highlight(placeOf(open.now(), 'fine'), placeOf(open.now(), 'in'));

  const marked = ['It went «fine (more or less) in» the end.', 'We were lucky.', 'That was all.'];
  assert.deepEqual(lines(open.now()), marked);
  const again = await panelOn(talk, moreOrLess(), open.store);
  assert.deepEqual(lines(again.now()), marked);
  // What is saved has the shape it always had: the cue's time range, and the words with one space between them.
  assert.deepEqual(ranges(again.now()), [['fine (more or less) in', 10, 14]]);
  assert.deepEqual(Object.keys(savedTalk(open.store).highlights[0]).sort(), ['end', 'id', 'made', 'start', 'transcript', 'words']);
});

/** A store that keeps one Highlight of the talk, as a build before this one saved it. */
async function keptBefore(highlight) {
  const store = standInStore();
  await store.set({ formatVersion: 1, 'video:youtube:iG9CE55wbtY': { title: talk.title, channel: talk.channel, highlights: [highlight] } });
  return store;
}
// What the build before bracketed phrases were found again saved for a Highlight in the cue from 10 to 14 s.
const savedBefore = (words, more = {}) => ({ id: 'kept-before', start: 10, end: 14, words, transcript: { language: 'en', source: 'uploader' }, made: '2026-10-07T21:19:09.117Z', ...more });

test('a word inside a bracketed phrase is not one of the words a Highlight counts itself among, so one saved as the second of two still shows where it did', async () => {
  // The cue says "the" twice as a word of its own, and once more inside the bracketed phrase.
  const said = () => cues([10, 14, 'the cat (on the mat) saw the dog']);
  // A Highlight of the "the" before "dog", as it was saved: the second of the two, counted from 0.
  const store = await keptBefore(savedBefore('the', { occurrence: 1 }));

  const open = await panelOn(talk, said(), store);

  assert.deepEqual(lines(open.now()), ['the cat (on the mat) saw «the» dog']);
  // One made now of the same word is saved with the same count, and nothing else is.
  await open.panel.highlight(placeOf(open.now(), 'the', 1), placeOf(open.now(), 'the', 1));
  const [, made] = open.now().highlights;
  assert.deepEqual({ ...made, id: 'kept-before', made: '2026-10-07T21:19:09.117Z' }, savedBefore('the', { occurrence: 1 }));
  assert.deepEqual(lines(open.now()), ['the cat (on the mat) saw ««the»» dog']);
});

test('a Highlight saved before, with a bracketed phrase among its words, finds its mark, and what is kept for it is not touched', async () => {
  // Before, such a Highlight never found its words and marked the whole of its cue, both sentences of it.
  const store = await keptBefore(savedBefore('fine (more or less) in'));
  const kept = store.everything();

  const open = await panelOn(talk, moreOrLess(), store);

  assert.deepEqual(lines(open.now()), ['It went «fine (more or less) in» the end.', 'We were lucky.', 'That was all.']);
  assert.deepEqual(store.everything(), kept);
  assert.equal(kept.formatVersion, 1);
});

test('of two bracketed phrases alike in one cue, a Highlight of the second says that it is the second, and marks it', async () => {
  const said = () => cues([10, 14, 'so (more or less) yes and (more or less) no']);
  const open = await panelOn(talk, said());

  await open.panel.highlight(placeOf(open.now(), '(more or less)', 1), placeOf(open.now(), 'no'));

  assert.deepEqual({ words: open.now().highlights[0].words, occurrence: open.now().highlights[0].occurrence }, { words: '(more or less) no', occurrence: undefined });
  await open.panel.highlight(placeOf(open.now(), '(more or less)', 1), placeOf(open.now(), '(more or less)', 1));
  const second = open.now().highlights.find((highlight) => highlight.words === '(more or less)');
  assert.equal(second.occurrence, 1);
  assert.deepEqual(lines(open.now()), ['so (more or less) yes and ««(more or less)» no»']);
  assert.deepEqual(lines((await panelOn(talk, said(), open.store)).now()), ['so (more or less) yes and ««(more or less)» no»']);
});

test('a bracketed phrase is found by its letters too, on a Transcript that writes it as words of their own and on one that brackets it', async () => {
  // The same four seconds as the auto-generated captions would have them: no brackets, no capitals, no full stops.
  const wordTimed = () => ({ language: 'en', source: 'auto-generated', timing: 'word', pieces: 'it went fine more or less in the end we were lucky'.split(' ').map((text, i) => ({ text, start: 10 + i * 0.3 })) });

  // Made on the uploader's captions, shown on the auto-generated ones.
  const first = await panelOn(talk, moreOrLess());
  await first.panel.highlight(placeOf(first.now(), 'fine'), placeOf(first.now(), 'in'));
  assert.deepEqual(lines((await panelOn(talk, wordTimed(), first.store)).now()), ['it went «fine more or less in» the end we were lucky']);

  // Made on the auto-generated captions, shown on the uploader's.
  const second = await panelOn(talk, wordTimed());
  await select(second, 'fine more or less in');
  assert.deepEqual(lines((await panelOn(talk, moreOrLess(), second.store)).now()), ['It went «fine (more or less) in» the end.', 'We were lucky.', 'That was all.']);
});

test('a bracketed phrase that runs over a line break of its cue is found again as one with a space in it is', async () => {
  // Captions break a cue into lines, and a bracket can open on one line and close on the next.
  const said = () => cues([10, 14, 'It went fine (more\nor less) in the end. We were lucky.']);
  const open = await panelOn(talk, said());
  assert.equal(open.now().transcript.words[3].text, '(more\nor less)');

  await open.panel.highlight(placeOf(open.now(), 'fine'), placeOf(open.now(), 'in'));

  const marked = ['It went «fine (more\nor less) in» the end.', 'We were lucky.'];
  assert.deepEqual(lines(open.now()), marked);
  // And on a Transcript that writes it on one line, where only the white space differs.
  assert.deepEqual(lines((await panelOn(talk, moreOrLess(), open.store)).now()), ['It went «fine (more or less) in» the end.', 'We were lucky.', 'That was all.']);
});

test('overlapping Highlights are allowed and stay separate: where they share words, the one that starts later is marked inside the other', async () => {
  const open = await panelOn(talk, saying('One two three four five six seven.'));

  await select(open, 'two three four five');
  await select(open, 'four five six');

  const [outer, inner] = open.now().highlights;
  assert.deepEqual([outer.words, inner.words], ['two three four five', 'four five six']);
  assert.deepEqual(lines(open.now()), ['One «two three «four five»»« six» seven.']);
  // Each mark says whose it is. The space before "six" belongs to the second Highlight alone.
  assert.deepEqual(open.now().marks.get(0), [
    0,
    ' ',
    { highlight: outer.id, parts: [1, ' ', 2, ' ', { highlight: inner.id, parts: [3, ' ', 4] }] },
    { highlight: inner.id, parts: [' ', 5] },
    ' ',
    6,
  ]);
  assert.equal(open.store.everything()['video:youtube:iG9CE55wbtY'].highlights.length, 2);
});

test('selecting the same words twice makes two Highlights', async () => {
  const open = await panelOn(talk, saying('One two three four.'));

  await select(open, 'two three');
  await select(open, 'two three');

  assert.deepEqual(open.now().highlights.map((highlight) => highlight.words), ['two three', 'two three']);
  assert.notEqual(open.now().highlights[0].id, open.now().highlights[1].id);
  assert.deepEqual(lines(open.now()), ['One ««two three»» four.']);
});

test("a video's Highlights are kept and shown in the order they come in the video", async () => {
  const open = await panelOn(talk, saying('One two three four five six seven.'));

  await select(open, 'six seven.');
  await select(open, 'two three');
  await select(open, 'two');

  // Of two that start together, the shorter comes first.
  const inTimeOrder = ['two', 'two three', 'six seven.'];
  assert.deepEqual(open.now().highlights.map((highlight) => highlight.words), inTimeOrder);
  assert.deepEqual(open.store.everything()['video:youtube:iG9CE55wbtY'].highlights.map((highlight) => highlight.words), inTimeOrder);
});

test('removing a Highlight takes its mark away and leaves the others, and it is still gone when the video is reopened', async () => {
  const first = await panelOn(dinner, recentAutoGenerated());
  await select(first, 'remain seated.');
  await select(first, 'not necessary.');
  const [seated, necessary] = first.now().highlights;

  await first.panel.removeHighlight(seated.id);

  assert.deepEqual(first.now().highlights, [necessary]);
  assert.deepEqual(lines(first.now()).slice(4, 6), ['Please remain seated.', "That's «not necessary.»"]);
  assert.deepEqual(first.store.everything()['video:youtube:rddfPNBNAJs'].highlights, [necessary]);

  const again = await panelOn(dinner, recentAutoGenerated(), first.store);

  assert.deepEqual(again.now().highlights, [necessary]);
  assert.deepEqual(lines(again.now()).slice(4, 6), ['Please remain seated.', "That's «not necessary.»"]);
});

test('opening a Highlight shows it as the one that is open, without moving the video, until it is closed or removed', async () => {
  const open = await panelOn(dinner, recentAutoGenerated());
  await open.player.seekTo(600);
  await select(open, 'remain seated.');
  await select(open, 'not necessary.');
  const [seated, necessary] = open.now().highlights;
  assert.equal(open.now().open, null, 'making a Highlight does not open it');

  open.panel.openHighlight(necessary.id);
  assert.deepEqual(open.now().open, necessary);
  assert.equal(await open.player.currentTime(), 600);

  // Another one opened takes its place.
  open.panel.openHighlight(seated.id);
  assert.deepEqual(open.now().open, seated);

  open.panel.closeHighlight();
  assert.equal(open.now().open, null);

  open.panel.openHighlight(seated.id);
  await open.panel.removeHighlight(seated.id);
  assert.equal(open.now().open, null);
  assert.deepEqual(open.now().highlights, [necessary]);
});

const realCaptionsOf = (video) => (video.id === talk.id ? fromTheUploader() : recentAutoGenerated());
const words = ({ highlights }) => highlights.map((highlight) => highlight.words);

test("each video keeps its own Highlights: moving to another video takes them off at once and shows that video's", async () => {
  const open = await panelOn(talk, realCaptionsOf);
  await select(open, 'blown away by the whole thing.');
  open.panel.openHighlight(open.now().highlights[0].id);

  open.player.goTo(dinner);
  await open.panel.refresh();

  // Gone before the store has answered for the next video, and nothing is open.
  assert.deepEqual([open.now().video, open.now().highlights, open.now().marks.size, open.now().open], [dinner, [], 0, null]);

  await settled();
  await select(open, 'remain seated.');
  assert.deepEqual(words(open.now()), ['remain seated.']);

  open.player.goTo(talk);
  await open.panel.refresh();
  await settled();

  assert.deepEqual(words(open.now()), ['blown away by the whole thing.']);
  assert.equal(lines(open.now())[5], "I've been «blown away by the whole thing.»");
  assert.deepEqual(Object.keys(open.store.everything()).sort(), ['formatVersion', 'video:youtube:iG9CE55wbtY', 'video:youtube:rddfPNBNAJs']);
});

test("Highlights the store gives after the tab has moved to another video are not shown on that video", async () => {
  const store = standInStore();
  await select(await panelOn(talk, realCaptionsOf, store), 'blown away by the whole thing.');

  // A store that answers each question about a video only when the test lets it. (The panel also reads its settings, at once.)
  const asked = [];
  const slow = { ...store, get: (key) => (key.startsWith('video:') ? new Promise((answer) => asked.push(async () => answer(await store.get(key)))) : store.get(key)) };
  const shown = [];
  const player = standInPlayer({ video: talk });
  const panel = createPanel({ player, fetchTranscript: async (video) => realCaptionsOf(video), store: slow, show: (state) => shown.push(state) });

  await panel.refresh();
  player.goTo(dinner);
  await panel.refresh();
  await asked[1]();
  await asked[0]();
  await settled();

  assert.deepEqual([shown.at(-1).video, shown.at(-1).highlights, shown.at(-1).marks.size], [dinner, [], 0]);
});

test('Highlights made or removed at the same moment are each kept or gone: none writes over another', async () => {
  const open = await panelOn(talk, saying('One two three four five six seven.'));
  await select(open, 'One');
  const [one] = open.now().highlights;

  await Promise.all([select(open, 'two three'), open.panel.removeHighlight(one.id), select(open, 'five six')]);

  assert.deepEqual(words(open.now()), ['two three', 'five six']);
  assert.deepEqual(words(open.store.everything()['video:youtube:iG9CE55wbtY']), ['two three', 'five six']);
});

const savedTalk = (store) => store.everything()['video:youtube:iG9CE55wbtY'];

test("the video's title and channel are saved at its first mark, and stay as they were then", async () => {
  const first = await panelOn(talk, saying('One two three four.'));
  await select(first, 'two');

  // The video has been renamed since, and is marked again.
  const renamed = { id: talk.id, title: 'Do schools still kill creativity?', channel: 'TED Talks' };
  const again = await panelOn(renamed, saying('One two three four.'), first.store);
  await select(again, 'three');

  assert.deepEqual([savedTalk(first.store).title, savedTalk(first.store).channel], ['Do schools kill creativity?', 'TED']);
  assert.deepEqual(words(savedTalk(first.store)), ['two', 'three']);
});

test('a first mark made before the page has said the title saves the title as soon as the page says it', async () => {
  // The page names a video a moment before it knows its title and channel.
  const open = await panelOn({ id: talk.id, title: '', channel: '' }, saying('One two three four.'));
  await select(open, 'two');
  assert.deepEqual([savedTalk(open.store).title, savedTalk(open.store).channel], ['', '']);

  open.player.goTo(talk);
  await open.panel.refresh();
  await settled();

  assert.deepEqual([savedTalk(open.store).title, savedTalk(open.store).channel], ['Do schools kill creativity?', 'TED']);
  assert.deepEqual(words(savedTalk(open.store)), ['two']);
});

test('a video that has never been marked has nothing saved, however often the page names it', async () => {
  const open = await panelOn({ id: talk.id, title: '', channel: '' }, saying('One two three four.'));

  open.player.goTo(talk);
  await open.panel.refresh();
  await settled();

  assert.deepEqual(open.store.everything(), {});
});

test('with no Transcript on show, nothing is made and nothing is saved', async () => {
  const waiting = await panelOn(talk, () => new Promise(() => {}));
  const none = await panelOn(talk, null);
  const failed = await panelOn(talk, () => Promise.reject(new Error('The player gave no token in 90 s.')));
  const noVideo = await panelOn(null, null);
  assert.deepEqual(
    [waiting, none, failed, noVideo].map((open) => open.now().transcript?.status),
    ['getting', 'none', 'failed', undefined]
  );

  for (const open of [waiting, none, failed, noVideo]) {
    await open.panel.highlight(0, 1);
    await open.panel.removeHighlight('no such Highlight');
    open.panel.openHighlight('no such Highlight');

    assert.deepEqual([open.now().highlights, open.now().open], [[], null]);
    assert.deepEqual(open.store.everything(), {});
  }
});

test("a video's saved Highlights are on show before its Transcript arrives and when it has none, and can be removed there", async () => {
  const store = standInStore();
  await select(await panelOn(talk, fromTheUploader(), store), 'blown away by the whole thing.');

  const waiting = await panelOn(talk, () => new Promise(() => {}), store);
  assert.equal(waiting.now().transcript.status, 'getting');
  assert.deepEqual(words(waiting.now()), ['blown away by the whole thing.']);
  assert.equal(waiting.now().marks.size, 0, 'with no lines on show there is nothing to mark');

  const none = await panelOn(talk, null, store);
  assert.equal(none.now().transcript.status, 'none');
  assert.deepEqual(words(none.now()), ['blown away by the whole thing.']);

  await none.panel.removeHighlight(none.now().highlights[0].id);
  assert.deepEqual(none.now().highlights, []);
  assert.deepEqual(savedTalk(store).highlights, []);
});

test('the marks on show are the same object from one showing to the next, until a Highlight or the Transcript changes', async () => {
  const open = await panelOn(talk, fromTheUploader());
  await select(open, 'blown away by the whole thing.');
  const marks = open.now().marks;

  // The page says the video's title again; a Highlight is opened and closed.
  await open.panel.refresh();
  open.panel.openHighlight(open.now().highlights[0].id);
  open.panel.closeHighlight();
  assert.equal(open.now().marks, marks, 'so the page can leave its lines alone');

  await select(open, 'Good morning.');
  assert.notEqual(open.now().marks, marks);
});

test('when the store fails to keep a Highlight, no mark is shown for it, and the next one is kept all the same', async () => {
  const store = standInStore();
  let failing = true;
  const flaky = { ...store, set: (entries) => (failing ? Promise.reject(new Error('No room left.')) : store.set(entries)) };
  const open = await panelOn(talk, saying('One two three four.'), flaky);

  await assert.rejects(select(open, 'two'), /No room left\./);
  assert.deepEqual([open.now().highlights, open.now().marks.size], [[], 0]);

  failing = false;
  await select(open, 'three');
  assert.deepEqual(words(open.now()), ['three']);
  assert.deepEqual(lines(open.now()), ['One two «three» four.']);
});

// Colours. A Highlight is one of three, and which one is one more thing it saves.

test('a Highlight is made yellow, the default of its three colours, and saves no colour for it', async () => {
  const open = await panelOn(talk, saying("It's been great. I've been blown away by the whole thing."));

  await select(open, 'blown away');

  const [made] = open.now().highlights;
  assert.deepEqual(COLOURS, ['yellow', 'green', 'purple']);
  assert.equal(colourOf(made), 'yellow');
  // Nothing is asked and nothing more is saved: the mark names no colour, and neither does what is kept.
  assert.deepEqual(lines(open.now()), ["It's been great.", "I've been «blown away» by the whole thing."]);
  assert.deepEqual(Object.keys(savedTalk(open.store).highlights[0]).sort(), ['end', 'id', 'made', 'start', 'transcript', 'words']);
});

test('picking another colour for a Highlight recolours its mark in every line it covers, and is saved', async () => {
  const open = await panelOn(talk, saying("It's been great. I've been blown away. In fact I'm leaving."));
  await select(open, 'blown away. In fact');
  const [made] = open.now().highlights;
  open.panel.openHighlight(made.id);

  await open.panel.colourHighlight(made.id, 'green');

  assert.deepEqual(lines(open.now()), ["It's been great.", "I've been «green:blown away.»", "«green:In fact» I'm leaving."]);
  // It is the same Highlight with one more thing saved, and it is still the one open.
  assert.deepEqual(open.now().highlights, [{ ...made, colour: 'green' }]);
  assert.deepEqual(savedTalk(open.store).highlights, [{ ...made, colour: 'green' }]);
  assert.equal(colourOf(open.now().open), 'green');
});

test('the default can be picked again, and the Highlight is then kept as it was before it had a colour', async () => {
  const open = await panelOn(talk, saying("It's been great. I've been blown away by the whole thing."));
  await select(open, 'blown away');
  const [made] = open.now().highlights;
  await open.panel.colourHighlight(made.id, 'purple');
  assert.deepEqual(lines(open.now()), ["It's been great.", "I've been «purple:blown away» by the whole thing."]);

  await open.panel.colourHighlight(made.id, 'yellow');

  assert.deepEqual(lines(open.now()), ["It's been great.", "I've been «blown away» by the whole thing."]);
  // No colour is saved for the default, so one that went back to it and one that never left it are kept alike.
  assert.deepEqual(savedTalk(open.store).highlights, [made]);
  assert.equal(colourOf(open.now().highlights[0]), 'yellow');
});

test('a Highlight saved with no colour, as every one was before there were colours, shows in the default', async () => {
  // What Chrome's storage held after the first Highlight ever made in a real side panel, with the video's name added.
  const store = standInStore();
  const before = {
    id: 'f83567bf-1cb6-4584-97c9-9b19c9cbfd86',
    start: 33.408,
    end: 35.729,
    words: 'blown away by the whole thing.',
    transcript: { language: 'en', source: 'uploader' },
    made: '2026-10-07T21:19:09.117Z',
  };
  await store.set({ formatVersion: 1, 'video:youtube:iG9CE55wbtY': { title: talk.title, channel: talk.channel, highlights: [before] } });

  const open = await panelOn(talk, fromTheUploader(), store);

  assert.equal(lines(open.now())[5], "I've been «blown away by the whole thing.»");
  assert.equal(colourOf(open.now().highlights[0]), 'yellow');
  // Showing it changes nothing that is kept, and the format's number is the same.
  assert.deepEqual(store.everything(), { formatVersion: 1, 'video:youtube:iG9CE55wbtY': { title: talk.title, channel: talk.channel, highlights: [before] } });
});

test("a Highlight's colour is the same when the video is reopened", async () => {
  const first = await panelOn(dinner, recentAutoGenerated());
  await select(first, 'remain seated.');
  await select(first, 'not necessary.');
  await first.panel.colourHighlight(first.now().highlights[1].id, 'purple');

  // The tab is closed and the video opened again: another panel, the same store.
  const again = await panelOn(dinner, recentAutoGenerated(), first.store);

  assert.deepEqual(lines(again.now()).slice(4, 6), ['Please «remain seated.»', "That's «purple:not necessary.»"]);
  assert.deepEqual(again.now().highlights.map(colourOf), ['yellow', 'purple']);
});

test('each Highlight has its own colour: recolouring one leaves the others as they are, also where they share words', async () => {
  const open = await panelOn(talk, saying('One two three four five six seven.'));
  await select(open, 'two three four five');
  await select(open, 'four five six');
  const [outer, inner] = open.now().highlights;

  await open.panel.colourHighlight(outer.id, 'green');

  assert.deepEqual(lines(open.now()), ['One «green:two three «four five»»« six» seven.']);
  assert.deepEqual(savedTalk(open.store).highlights, [{ ...outer, colour: 'green' }, inner]);

  await open.panel.colourHighlight(inner.id, 'purple');

  assert.deepEqual(lines(open.now()), ['One «green:two three «purple:four five»»«purple: six» seven.']);

  // The next one made is yellow again, whatever colour was picked last.
  await select(open, 'One');
  assert.deepEqual(lines(open.now()), ['«One» «green:two three «purple:four five»»«purple: six» seven.']);
});

test('a Highlight removed at the same moment as it is recoloured stays removed', async () => {
  const open = await panelOn(talk, saying('One two three four.'));
  await select(open, 'two three');
  await select(open, 'four.');
  const [made, other] = open.now().highlights;

  await Promise.all([open.panel.removeHighlight(made.id), open.panel.colourHighlight(made.id, 'green')]);

  assert.deepEqual(open.now().highlights, [other]);
  assert.deepEqual(savedTalk(open.store).highlights, [other]);
});

test('only the three colours are saved: any other is not taken, and a Highlight kept with one shows in the default', async () => {
  const open = await panelOn(talk, saying('One two three four.'));
  await select(open, 'two three');
  const [made] = open.now().highlights;

  await open.panel.colourHighlight(made.id, 'red');

  assert.deepEqual(savedTalk(open.store).highlights, [made]);
  assert.deepEqual(lines(open.now()), ['One «two three» four.']);

  // One that is kept with another colour all the same, written by something other than this panel.
  await open.store.set({ 'video:youtube:iG9CE55wbtY': { ...savedTalk(open.store), highlights: [{ ...made, colour: 'red' }] } });
  const again = await panelOn(talk, saying('One two three four.'), open.store);

  assert.equal(colourOf(again.now().highlights[0]), 'yellow');
  assert.deepEqual(lines(again.now()), ['One «two three» four.']);
});

// The plain functions the panel is built on. The tickets after this one call
// them too: to make a Highlight by key, to put back one that was removed, and
// to save one again with a Note or a colour.

/** A Transcript as the panel holds one that is ready. */
const ready = (transcript) => ({ status: 'ready', line: null, ...transcript, ...cutIntoSentences(transcript) });

test('a Highlight is made, saved, placed and removed by plain functions, and one saved again under its id takes the place of the one kept', async () => {
  const store = standInStore();
  const uploaders = ready(fromTheUploader());
  // "I've been blown away by the whole thing." is words 12 to 19.
  const made = highlightOf(uploaders, 14, 19, { id: 'first', made: new Date('2026-10-07T18:30:00Z') });
  assert.deepEqual(made, {
    id: 'first',
    start: 33.408,
    end: 35.729,
    words: 'blown away by the whole thing.',
    transcript: { language: 'en', source: 'uploader' },
    made: '2026-10-07T18:30:00.000Z',
  });
  assert.deepEqual(await saveHighlight(store, talk, made), [made]);
  assert.deepEqual(placeHighlight(uploaders, made), { first: 14, last: 19 });

  // The same Highlight with other words, and with a field this ticket knows nothing of.
  const grown = { ...highlightOf(uploaders, 12, 19, { id: 'first', made: new Date(made.made) }), colour: 'green' };
  assert.deepEqual(await saveHighlight(store, talk, grown), [grown]);
  assert.deepEqual(await highlightsOf(store, talk.id), [grown]);
  assert.deepEqual(placeHighlight(uploaders, grown), { first: 12, last: 19 });

  assert.deepEqual(await removeHighlight(store, talk.id, 'first'), []);
  assert.deepEqual(await highlightsOf(store, talk.id), []);
});
