// H keeps the sentence just spoken: which sentence that is, the Highlight it
// makes, and how H again reaches one sentence further back. The rule is the
// prototype's, but for one thing since ticket 23: H grows only a Highlight that H made,
// where the prototype's H grew one made by selecting as well.

import assert from 'node:assert/strict';

import { colourOf } from '../src/core/highlights.js';
import { reachBack, sentenceJustSpoken } from '../src/core/just-spoken.js';
import { cutIntoSentences } from '../src/core/transcript.js';
import { dinner, lines, marked, morning, panelOn, pressHAt, saying, select, settled, talk, wordsOf } from './open-panel.js';
import { fromTheUploader, oldAutoGenerated, recentAutoGenerated, test } from './real-captions.js';

const sentencesOf = (transcript) => cutIntoSentences(transcript).sentences;
/** The sentence H takes at a time, as its text, or null when it takes none. */
const taken = (transcript, seconds) => {
  const sentences = sentencesOf(transcript);
  return sentences[sentenceJustSpoken(sentences, seconds)]?.text ?? null;
};

test('H takes the sentence that was being said 1.2 s earlier', () => {
  // "Good morning." from 10 s, "How are you?" from 12 s, "Fine." from 20 s.
  const greeting = saying([10, 'Good morning.'], [12, 'How are you?'], [20, 'Fine.']);

  // At 13 s "How are you?" is being said, and 1.2 s earlier "Good morning." still was.
  assert.equal(taken(greeting, 13), 'Good morning.');
  assert.equal(taken(greeting, 13.2), 'How are you?');
  // A sentence stays the one through the silence after it.
  assert.equal(taken(greeting, 21.1), 'How are you?');
  assert.equal(taken(greeting, 21.2), 'Fine.');
});

test('H skips a bracketed sound, back to what was last said', () => {
  const applause = saying([10, 'Thank you.'], [12, '[applause]'], [14, '[Music]'], [20, 'Please remain seated.']);

  // 1.2 s before 13.5 s and before 16 s there was only applause and music.
  assert.equal(taken(applause, 13.5), 'Thank you.');
  assert.equal(taken(applause, 16), 'Thank you.');
  assert.equal(taken(applause, 21.2), 'Please remain seated.');
});

test('H takes nothing before anything has been said', () => {
  const opening = saying([2, '[Music]'], [10, 'Good morning.']);

  assert.equal(taken(opening, 0), null);
  assert.equal(taken(opening, 1), null);
  // Music is not something said, and 1.2 s before 11.1 s nothing else had been.
  assert.equal(taken(opening, 5), null);
  assert.equal(taken(opening, 11.1), null);
  assert.equal(taken(opening, 11.2), 'Good morning.');
});

test('on the real captions H takes the sentence that was being said 1.2 s earlier, word-timed or cue-timed', () => {
  // Auto-generated in 2026, a time for every word: "Please remain seated." from 4 s, "That's not necessary." from 5.16 s.
  assert.equal(taken(recentAutoGenerated(), 6.3), 'Please remain seated.');
  assert.equal(taken(recentAutoGenerated(), 6.4), "That's not necessary.");
  // The first line is [applause], from 0.654 s, and "Thank you." comes at 0.8 s.
  assert.equal(taken(recentAutoGenerated(), 1.9), null);
  assert.equal(taken(recentAutoGenerated(), 2), 'Thank you.');

  // The uploader's captions, timed per cue: "In fact, I'm leaving." from 35.753 s, (Laughter) from 37.269 s
  // until "There have been three themes…" at 43.096 s. H during the laughter takes what was said before it.
  assert.equal(taken(fromTheUploader(), 38), "In fact, I'm leaving.");
  assert.equal(taken(fromTheUploader(), 44.2), "In fact, I'm leaving.");
  assert.match(taken(fromTheUploader(), 44.3), /^There have been three themes/);

  // Auto-generated in 2007, with no punctuation: [Music] from 6.26 s, "good morning" from 26.56 s, "how are you" from 28.4 s.
  assert.equal(taken(oldAutoGenerated(), 20), null);
  assert.equal(taken(oldAutoGenerated(), 29.5), 'good morning');
  assert.equal(taken(oldAutoGenerated(), 29.6), 'how are you');
});

// ------------------------------------------------------------ through the panel
test('pressing H makes a Highlight of the sentence that was being said 1.2 s earlier', async () => {
  const open = await panelOn(talk, saying([10, 'Good morning.'], [12, 'How are you?'], [20, 'Fine.']));

  await pressHAt(open, 13);

  assert.deepEqual(lines(open.now()), ['«Good morning.»', 'How are you?', 'Fine.']);
  assert.deepEqual(wordsOf(open.now()), ['Good morning.']);
});

test('a Highlight made with H is saved as one made by selecting is: its time range, its words, its Transcript and when it was made', async () => {
  // Word-timed. "Please remain seated." is timed at 4, 4.36 and 4.72 s, and the next word comes at 5.16 s.
  const wordTimed = await panelOn(dinner, recentAutoGenerated());
  await pressHAt(wordTimed, 6);

  const [saved] = wordTimed.now().highlights;
  assert.deepEqual(wordTimed.store.everything(), {
    formatVersion: 1,
    'video:youtube:rddfPNBNAJs': {
      title: 'Remarks after dinner',
      channel: 'The Dinner',
      highlights: [{ id: saved.id, start: 4, end: 5.16, words: 'Please remain seated.', transcript: { language: 'en', source: 'auto-generated' }, made: saved.made }],
    },
  });
  assert.match(saved.id, /^\S+$/);
  assert.equal(new Date(saved.made).toISOString(), saved.made);

  // Cue-timed. "It's been great, hasn't it?" is the whole of one cue, from 31.129 to 32.797 s.
  const cueTimed = await panelOn(talk, fromTheUploader());
  await pressHAt(cueTimed, 33);

  assert.deepEqual(marked(cueTimed.now()), ["«It's been great, hasn't it?»"]);
  assert.deepEqual(
    cueTimed.now().highlights.map(({ start, end, words, transcript }) => ({ start, end, words, transcript })),
    [{ start: 31.129, end: 32.797, words: "It's been great, hasn't it?", transcript: { language: 'en', source: 'uploader' } }]
  );
});

test('H makes nothing while there is no sentence to take: before anything is said, and during an advert', async () => {
  const open = await panelOn(talk, saying([2, '[Music]'], [10, 'Good morning.'], [12, 'How are you?']));

  await pressHAt(open, 1);
  await pressHAt(open, 11);
  assert.deepEqual(open.now().highlights, []);

  // While an advert plays the player cannot say the time.
  open.player.playTo(13);
  open.player.advert(true);
  await open.panel.keyPressed('h');
  assert.deepEqual(open.now().highlights, []);

  open.player.advert(false);
  await open.panel.keyPressed('h');
  assert.deepEqual(wordsOf(open.now()), ['Good morning.']);
  assert.deepEqual(open.store.everything()['video:youtube:iG9CE55wbtY'].highlights.length, 1);
});

test('H makes nothing with no Transcript on show', async () => {
  const waiting = await panelOn(talk, new Promise(() => {}), { at: 13 }); // the Transcript never arrives
  const none = await panelOn(talk, null, { at: 13 });
  const noVideo = await panelOn(null, null, { at: 13 });

  for (const open of [waiting, none, noVideo]) {
    await open.panel.keyPressed('h');
    assert.deepEqual(open.now().highlights, []);
    assert.deepEqual(open.store.everything(), {});
  }
  assert.deepEqual([waiting.now().transcript.status, none.now().transcript.status, noVideo.now().transcript], ['getting', 'none', null]);
});

// ------------------------------------------------------------------- H again
// `morning()` says "Good morning." from 10 s, "How are you?" from 12 s, "It's been great." from 14 s
// and "I've been blown away." from 20 s.
test('H again within 3 s adds the sentence before to that same Highlight', async () => {
  const open = await panelOn(talk, morning());
  await pressHAt(open, 16); // "It's been great."
  const [made] = open.now().highlights;

  // Two seconds later, and wherever the video has got to by then.
  open.clock.pass(2);
  await pressHAt(open, 22);

  assert.deepEqual(lines(open.now()), ['Good morning.', '«How are you?»', "«It's been great.»", "I've been blown away."]);
  // One Highlight, the same one: its id and when it was made are as they were, and its words and its start are new.
  assert.deepEqual(open.now().highlights, [{ ...made, start: 12, words: "How are you? It's been great." }]);
  assert.deepEqual(open.store.everything()['video:youtube:iG9CE55wbtY'].highlights, open.now().highlights);
});

test('each H again starts the 3 s again, and once they are over H takes a sentence afresh', async () => {
  const open = await panelOn(talk, morning());
  await pressHAt(open, 16); // "It's been great."

  // 2.999 s after the first H, and then 2.999 s after the second: each is inside the 3 s of the one before.
  open.clock.pass(2.999);
  await open.panel.keyPressed('h');
  assert.deepEqual(wordsOf(open.now()), ["How are you? It's been great."]);
  open.clock.pass(2.999);
  await open.panel.keyPressed('h');
  assert.deepEqual(wordsOf(open.now()), ["Good morning. How are you? It's been great."]);

  // Exactly 3 s after the last one the 3 s are over: H makes a Highlight of what was just said.
  open.clock.pass(3);
  await pressHAt(open, 22);
  assert.deepEqual(lines(open.now()), ['«Good morning.»', '«How are you?»', "«It's been great.»", "«I've been blown away.»"]);
  assert.deepEqual(wordsOf(open.now()), ["Good morning. How are you? It's been great.", "I've been blown away."]);
});

test('H again reaches back over a bracketed sound to what was said before it, on the real cue-timed captions', async () => {
  // "In fact, I'm leaving." is one cue, 35.753 to 37.245 s. Then (Laughter), and from 43.096 s two cues
  // hold "There have been three themes running through the conference, which are relevant to what I want
  // to talk about.", the second ending at 48.973 s.
  const open = await panelOn(talk, fromTheUploader());
  await pressHAt(open, 45);
  assert.deepEqual(marked(open.now()), ['«There have been three themes running through the conference, which are relevant to what I want to talk about.»']);

  await open.panel.keyPressed('h');

  assert.deepEqual(marked(open.now()), ["«In fact, I'm leaving.»", '«(Laughter)»', '«There have been three themes running through the conference, which are relevant to what I want to talk about.»']);
  assert.deepEqual(
    open.now().highlights.map(({ start, end, words }) => ({ start, end, words })),
    [{ start: 35.753, end: 48.973, words: "In fact, I'm leaving. (Laughter) There have been three themes running through the conference, which are relevant to what I want to talk about." }]
  );
});

// ----------------------------------------------------------- cues that overlap
test('where cues overlap in time, H can take each line: pressed 1.2 s after a line starts, it takes that line', async () => {
  // "Fine." comes on at 11 s, while the cue before it stays up until 14 s. Two more cues come on together at 14 s.
  const open = await panelOn(talk, cues([10, 14, 'Good morning. How are you?'], [11, 13, 'Fine.'], [14, 16, 'And you?'], [14, 16, 'Very well.'], [16, 18, 'Good.']));
  const { sentences } = open.now().transcript;
  assert.deepEqual(sentences.map((sentence) => sentence.text), ['Good morning.', 'How are you?', 'Fine.', 'And you?', 'Very well.', 'Good.']);

  for (const sentence of sentences) {
    open.clock.pass(60); // long after the Highlight before it was made, so that H takes a sentence afresh
    await pressHAt(open, sentence.start + 1.2);
  }

  assert.deepEqual(wordsOf(open.now()), ['Good morning.', 'How are you?', 'Fine.', 'And you?', 'Very well.', 'Good.']);
  assert.deepEqual(lines(open.now()), ['«Good morning.»', '«How are you?»', '«Fine.»', '«And you?»', '«Very well.»', '«Good.»']);
});

// ------------------------------------------------------------------- colours
test('a Highlight made with H is in the default colour, yellow: it saves no colour at all, and its mark names none', async () => {
  const open = await panelOn(talk, morning());

  await pressHAt(open, 16);

  const [made] = open.now().highlights;
  assert.equal(colourOf(made), 'yellow');
  assert.equal('colour' in made, false);
  assert.deepEqual(Object.keys(open.store.everything()['video:youtube:iG9CE55wbtY'].highlights[0]).sort(), ['end', 'id', 'made', 'start', 'transcript', 'words']);
  // A mark names its colour only when it is not the default.
  assert.deepEqual(open.now().marks.get(2), [{ highlight: made.id, parts: [5, ' ', 6, ' ', 7] }]);
});

test('a Highlight given a colour and then grown with H keeps the colour', async () => {
  const open = await panelOn(talk, morning());
  await pressHAt(open, 16);
  const [made] = open.now().highlights;
  await open.panel.colourHighlight(made.id, 'green');

  open.clock.pass(2);
  await open.panel.keyPressed('h');

  assert.deepEqual(open.now().highlights, [{ ...made, start: 12, words: "How are you? It's been great.", colour: 'green' }]);
  assert.deepEqual(open.store.everything()['video:youtube:iG9CE55wbtY'].highlights, open.now().highlights);
  // Both of its lines are marked in that colour.
  assert.deepEqual([open.now().marks.get(1)[0].colour, open.now().marks.get(2)[0].colour], ['green', 'green']);
});

// --------------------------------------- the same words twice in a time range
/** A cue-timed Transcript of the uploader's, each cue a start, an end and its text. */
const cues = (...said) => ({ language: 'en', source: 'uploader', timing: 'cue', pieces: said.map(([start, end, text]) => ({ start, end, text })) });

test('H again works out afresh which of them a Highlight is, where its time range holds its words twice', async () => {
  // One cue says "Good." twice, as two sentences. Each is the cue's whole time range and the same word.
  const open = await panelOn(talk, cues([10, 12, 'Good. Good.'], [12, 14, 'Fine.']));
  await pressHAt(open, 12.5); // 1.2 s earlier the second "Good." was being said
  const [made] = open.now().highlights;
  assert.deepEqual(lines(open.now()), ['Good.', '«Good.»', 'Fine.']);
  assert.deepEqual({ words: made.words, occurrence: made.occurrence }, { words: 'Good.', occurrence: 1 });

  await open.panel.keyPressed('h');

  // "Good. Good." is in its time range once, so the grown Highlight no longer says which it is.
  assert.deepEqual(lines(open.now()), ['«Good.»', '«Good.»', 'Fine.']);
  assert.deepEqual(open.now().highlights, [{ id: made.id, start: 10, end: 12, words: 'Good. Good.', transcript: { language: 'en', source: 'uploader' }, made: made.made }]);
});

test('growing a Highlight back leaves alone anything else it carries', () => {
  // With something on it that this version of the extension knows nothing of. H again does this to the
  // Highlight H just made; a Highlight kept on another day is one H no longer grows, so it is asked here directly.
  const kept = { id: 'kept-before', start: 14, end: 16.5, words: "It's been great.", transcript: { language: 'en', source: 'auto-generated' }, made: '2026-10-01T09:00:00.000Z', colour: 'green', pinned: true };
  const transcript = { status: 'ready', line: null, ...morning(), ...cutIntoSentences(morning()) };

  assert.deepEqual(reachBack(transcript, kept), { ...kept, start: 12, words: "How are you? It's been great." });
});

test('H again changes nothing when nothing was said before the Highlight', async () => {
  const open = await panelOn(talk, saying([2, '[Music]'], [10, 'Good morning.'], [12, 'How are you?']));
  await pressHAt(open, 11.5);
  const made = open.now().highlights;
  assert.deepEqual(wordsOf(open.now()), ['Good morning.']);

  await open.panel.keyPressed('h');

  assert.deepEqual(open.now().highlights, made);
  assert.deepEqual(lines(open.now()), ['[Music]', '«Good morning.»', 'How are you?']);
});

// ---------------------------------------------- a sentence that is already one
test('H on a sentence that is already a Highlight makes no second one', async () => {
  const open = await panelOn(talk, morning());
  await pressHAt(open, 16); // "It's been great."
  const made = open.now().highlights;

  // Long after, with the video in the same sentence, or back in it.
  open.clock.pass(60);
  await pressHAt(open, 17);

  assert.deepEqual(open.now().highlights, made);
  assert.deepEqual(open.store.everything()['video:youtube:iG9CE55wbtY'].highlights, made);
  assert.deepEqual(lines(open.now()), ['Good morning.', 'How are you?', "«It's been great.»", "I've been blown away."]);
});

test('H on a sentence that holds a bracketed phrase with a space in it, pressed again later, makes no second Highlight', async () => {
  // "(more or less)" is one word of the Transcript and three of the Highlight's saved words. The cue holds
  // a second sentence, so the Highlight's time range, the cue's, holds more than the sentence H took.
  const open = await panelOn(talk, cues([10, 14, 'It went fine (more or less) in the end. We were lucky.'], [14, 16, 'That was all.']));
  await pressHAt(open, 11.5);
  const made = open.now().highlights;
  assert.deepEqual(lines(open.now()), ['«It went fine (more or less) in the end.»', 'We were lucky.', 'That was all.']);

  open.clock.pass(9);
  await pressHAt(open, 11.5);

  assert.deepEqual(open.now().highlights, made);
  assert.deepEqual(open.store.everything()['video:youtube:iG9CE55wbtY'].highlights, made);
  // It is taken up instead, as any sentence that is already a Highlight is.
  assert.equal(open.panel.highlightJustMade()?.id, made[0].id);
});

test('that Highlight is then the one just made, for a Note, and H again does not grow it', async () => {
  // H on a sentence already kept takes up the Highlight that is there, so that N writes on it. Until
  // ticket 23 H again also grew it, as in the prototype. It does not now: how a Highlight was made is
  // not kept, so nothing says this one was not selected by hand, and one that was is never stretched.
  const open = await panelOn(talk, morning());
  await pressHAt(open, 16);
  const [made] = open.now().highlights;
  open.clock.pass(60);
  await pressHAt(open, 17);
  assert.equal(open.panel.highlightJustMade()?.id, made.id);

  open.clock.pass(3);
  await open.panel.keyPressed('h');

  assert.deepEqual(open.now().highlights, [made]);
  assert.equal(open.panel.highlightJustMade()?.id, made.id, 'taken up again, and its 5 s start again');

  // Once the video has played on, H takes the sentence then just spoken, and the first one is still as it was.
  open.clock.pass(3);
  await pressHAt(open, 22);
  assert.deepEqual(wordsOf(open.now()), ["It's been great.", "I've been blown away."]);
  assert.deepEqual(open.now().highlights[0], made);
});

test('only a Highlight of the whole sentence and no more counts as already there, as in the prototype', async () => {
  const open = await panelOn(talk, morning());
  // Two made by selecting, long before: part of one sentence, and that sentence with the one after it.
  await select(open, 'been great.');
  await select(open, "It's been great. I've been blown away.");
  open.clock.pass(60);

  await pressHAt(open, 16); // "It's been great."

  assert.deepEqual(wordsOf(open.now()), ["It's been great.", "It's been great. I've been blown away.", 'been great.']);

  // A Highlight made by selecting the sentence exactly is one H finds there.
  open.clock.pass(60);
  await select(open, "I've been blown away.");
  open.clock.pass(60);
  await pressHAt(open, 22);

  assert.equal(open.now().highlights.filter((highlight) => highlight.words === "I've been blown away.").length, 1);
});

// ------------------------------------------------- the Highlight just made
// Giovani, 2026-10-07: "make the timeout for H be 3 seconds", and of N's 8 s, "make that 5 sec". The 8 s were the prototype's for both keys.
test("H has 3 s to grow the Highlight it made, and N has 5 s to write on it: 4 s after, it is the one just made and H takes a sentence afresh", async () => {
  const open = await panelOn(talk, morning());
  await pressHAt(open, 16); // "It's been great."
  const [made] = open.now().highlights;

  open.clock.pass(4);
  assert.equal(open.panel.highlightJustMade()?.id, made.id);
  await pressHAt(open, 22); // "I've been blown away."

  assert.deepEqual(wordsOf(open.now()), ["It's been great.", "I've been blown away."]);
  assert.deepEqual(open.now().highlights[0], made);
});

test('for 5 s after a Highlight is made, by H or by selecting, the panel says it is the one just made', async () => {
  const open = await panelOn(talk, morning());
  assert.equal(open.panel.highlightJustMade(), null);

  await pressHAt(open, 16);
  const [byKey] = open.now().highlights;
  assert.deepEqual(open.panel.highlightJustMade(), byKey);
  open.clock.pass(4.999);
  assert.deepEqual(open.panel.highlightJustMade(), byKey);
  open.clock.pass(0.001);
  assert.equal(open.panel.highlightJustMade(), null);

  await select(open, 'blown away.');
  const bySelecting = open.now().highlights.find((highlight) => highlight.words === 'blown away.');
  assert.deepEqual(open.panel.highlightJustMade(), bySelecting);
  open.clock.pass(5);
  assert.equal(open.panel.highlightJustMade(), null);
});

// A Highlight the person selected by hand is never stretched: H grows only a Highlight that H made
// or last grew. (Until ticket 23, H soon after a selection grew the selected one, as the prototype did.)
test('H just after a Highlight made by selecting does not grow it: it takes the sentence just spoken as a Highlight of its own', async () => {
  const open = await panelOn(talk, morning());
  await select(open, 'blown away.');
  const [selected] = open.now().highlights;

  open.clock.pass(2);
  await pressHAt(open, 16); // 1.2 s earlier "It's been great." was being said

  assert.deepEqual(lines(open.now()), ['Good morning.', 'How are you?', "«It's been great.»", "I've been «blown away.»"]);
  assert.deepEqual(wordsOf(open.now()), ["It's been great.", 'blown away.']);
  assert.deepEqual(open.now().highlights[1], selected);
  assert.deepEqual(open.store.everything()['video:youtube:iG9CE55wbtY'].highlights[1], selected);
});

test('the Highlight H makes after a selection is then the one just made, so H again grows that one, and the selected one stays as it was', async () => {
  const open = await panelOn(talk, morning());
  await select(open, 'blown away.');
  const [selected] = open.now().highlights;
  open.clock.pass(2);
  await pressHAt(open, 16);
  const [made] = open.now().highlights;
  assert.equal(open.panel.highlightJustMade()?.id, made.id);

  open.clock.pass(2);
  await open.panel.keyPressed('h');

  assert.deepEqual(open.now().highlights, [{ ...made, start: 12, words: "How are you? It's been great." }, selected]);
});

test('H just after a selection does nothing while an advert plays: there is no sentence to take, and nothing of its own to grow', async () => {
  const open = await panelOn(talk, morning());
  await select(open, 'blown away.');
  const selected = open.now().highlights;
  open.clock.pass(2);
  open.player.playTo(16);
  open.player.advert(true);

  await open.panel.keyPressed('h');

  assert.deepEqual(open.now().highlights, selected);
  assert.deepEqual(open.store.everything()['video:youtube:iG9CE55wbtY'].highlights, selected);
});

test('a sentence selected whole by hand is a Highlight that H finds there and never stretches, inside its first 5 s or after them', async () => {
  const open = await panelOn(talk, morning());
  await select(open, "It's been great.");
  const selected = open.now().highlights;

  // Inside its 5 s H takes the sentence just spoken, which is that sentence: it makes no second Highlight of it.
  open.clock.pass(2);
  await pressHAt(open, 16);
  assert.deepEqual(open.now().highlights, selected);
  // H again straight after, H long after, and H again after that: none grows it.
  open.clock.pass(2);
  await open.panel.keyPressed('h');
  open.clock.pass(60);
  await open.panel.keyPressed('h');
  open.clock.pass(2);
  await open.panel.keyPressed('h');

  assert.deepEqual(open.now().highlights, selected);
  assert.deepEqual(open.store.everything()['video:youtube:iG9CE55wbtY'].highlights, selected);
});

test('a Highlight that is removed is no longer the one just made, and H then takes a sentence afresh', async () => {
  const open = await panelOn(talk, morning());
  await pressHAt(open, 16);
  await open.panel.removeHighlight(open.now().highlights[0].id);
  assert.equal(open.panel.highlightJustMade(), null);

  open.clock.pass(1);
  await pressHAt(open, 22);

  assert.deepEqual(wordsOf(open.now()), ["I've been blown away."]);
});

test('moving to another video ends it too, even if the tab comes back within the 5 s', async () => {
  const open = await panelOn(talk, morning());
  await pressHAt(open, 16);

  open.player.goTo(dinner);
  await open.panel.refresh();
  await settled();
  assert.equal(open.panel.highlightJustMade(), null);
  open.player.goTo(talk);
  await open.panel.refresh();
  await settled();

  assert.deepEqual(wordsOf(open.now()), ["It's been great."]);
  assert.equal(open.panel.highlightJustMade(), null);
});

test('H pressed twice at the same moment makes one Highlight and grows it, as two presses in turn do', async () => {
  const open = await panelOn(talk, morning());
  open.player.playTo(16);

  await Promise.all([open.panel.keyPressed('h'), open.panel.keyPressed('h')]);

  assert.deepEqual(wordsOf(open.now()), ["How are you? It's been great."]);
  assert.deepEqual(open.store.everything()['video:youtube:iG9CE55wbtY'].highlights.length, 1);
});

test('the key is H whether or not it comes as a capital, and any other key does nothing', async () => {
  const open = await panelOn(talk, morning());
  open.player.playTo(16);

  await open.panel.keyPressed('x');
  await open.panel.keyPressed('Enter');
  assert.deepEqual(open.now().highlights, []);

  await open.panel.keyPressed('H');
  assert.deepEqual(wordsOf(open.now()), ["It's been great."]);
});
