// The sentence rule against the three real sets of captions kept with the
// prototype. The lines expected here are what the prototype itself makes of
// the same captions (its own code was run over them when this was written),
// and each can be read off the captions by eye.

import assert from 'node:assert/strict';

import { cutIntoSentences } from '../src/core/transcript.js';
import { fromTheUploader, oldAutoGenerated, recentAutoGenerated, test } from './real-captions.js';

const opening = ({ sentences }, count) => sentences.slice(0, count).map((sentence) => [sentence.start, sentence.text]);
const longest = ({ sentences }) => Math.max(...sentences.map((sentence) => sentence.last - sentence.first + 1));

test('auto-generated captions with punctuation: cut at each full stop, each word with its own time', () => {
  const transcript = recentAutoGenerated();
  const cut = cutIntoSentences(transcript);

  assert.equal(transcript.timing, 'word');
  assert.deepEqual(opening(cut, 10), [
    [0.654, '[applause]'],
    [0.8, 'Thank you.'],
    [2.08, 'Thank you.'],
    [3.6, 'Thank you.'],
    [4, 'Please remain seated.'],
    [5.16, "That's not necessary."],
    [7.32, 'Thank you very much.'],
    [8, 'Please, Mr. President.'],
    [9.24, "Don't stand."],
    [9.92, "That wouldn't be right."],
  ]);
  // "Please remain seated." is three words, each said at its own time. The
  // captions give them as 400, 760 and 1120 ms into a caption that starts at 3600 ms.
  assert.deepEqual(
    cut.words.slice(cut.sentences[4].first, cut.sentences[4].last + 1).map((word) => [word.text, word.start]),
    [['Please', 4], ['remain', 4.36], ['seated.', 4.72]]
  );
  assert.deepEqual([cut.sentences.at(-1).start, cut.sentences.at(-1).text], [1635.4, 'Thank you very much.']);
  assert.equal(cut.words.length, 3587);
  assert.equal(cut.sentences.length, 380);
  assert.equal(cut.sentences.filter((sentence) => sentence.sound).length, 23, 'bracketed sounds, each on its own line');
  assert.equal(cut.sentences.filter((sentence) => sentence.newSpeaker).length, 45, 'sentences that start with a new speaker');
});

test("the uploader's captions: cut at each full stop though a cue holds more than one sentence", () => {
  const transcript = fromTheUploader();
  const cut = cutIntoSentences(transcript);

  assert.equal(transcript.timing, 'cue');
  assert.deepEqual(opening(cut, 9), [
    [27.103, 'Good morning.'],
    [28.49, 'How are you?'],
    [29.702, '(Audience)'],
    [30.667, 'Good.'],
    [31.129, "It's been great, hasn't it?"],
    [33.408, "I've been blown away by the whole thing."],
    [35.753, "In fact, I'm leaving."],
    [37.269, '(Laughter)'],
    [43.096, 'There have been three themes running through the conference, which are relevant to what I want to talk about.'],
  ]);
  assert.deepEqual([cut.sentences.at(-1).start, cut.sentences.at(-1).text], [1159.766, '(Applause)']);
  assert.equal(cut.words.length, 3170);
  assert.equal(cut.sentences.length, 321);
  assert.equal(cut.sentences.filter((sentence) => sentence.sound).length, 45);
});

test('auto-generated captions with no punctuation: cut at pauses of 0.7 s, and no sentence longer than 26 words', () => {
  const transcript = oldAutoGenerated();
  const cut = cutIntoSentences(transcript);

  assert.equal(transcript.timing, 'word');
  assert.deepEqual(opening(cut, 7), [
    [6.26, '[Music]'],
    [26.56, 'good morning'],
    [28.4, 'how are you'],
    [30.72, "it's been great hasn't it"],
    [32.96, "it's been i've been blown away by the whole thing in fact i'm leaving"],
    [40.399, 'um'],
    [42.8, 'there have been three themes haven\'t they running through the conference'],
  ]);
  assert.equal(longest(cut), 26);
  assert.equal(cut.words.length, 3337);
  assert.equal(cut.sentences.length, 384);
  assert.equal(cut.sentences.filter((sentence) => sentence.sound).length, 16);
});

test('every word of a Transcript is in one sentence, in the order it was spoken', () => {
  for (const transcript of [recentAutoGenerated(), fromTheUploader(), oldAutoGenerated()]) {
    const { words, sentences } = cutIntoSentences(transcript);

    assert.equal(sentences[0].first, 0);
    assert.equal(sentences.at(-1).last, words.length - 1);
    sentences.slice(1).forEach((sentence, i) => assert.equal(sentence.first, sentences[i].last + 1));
    words.slice(1).forEach((word, i) => assert.ok(word.start >= words[i].start, `"${word.text}" at ${word.start} s comes after ${words[i].start} s`));
  }
});

test('a Transcript holds timed pieces of text and nothing shaped by YouTube', () => {
  for (const transcript of [recentAutoGenerated(), fromTheUploader(), oldAutoGenerated()]) {
    assert.deepEqual(Object.keys(transcript).sort(), ['language', 'pieces', 'source', 'timing']);
    const fields = new Set(transcript.pieces.flatMap((piece) => Object.keys(piece)));
    assert.deepEqual([...fields].sort(), transcript.timing === 'cue' ? ['end', 'start', 'text'] : ['newSpeaker', 'start', 'text'].filter((field) => fields.has(field)));
    assert.ok(transcript.pieces.every((piece) => typeof piece.text === 'string' && typeof piece.start === 'number'));
  }
});
