// Fetching a video's Transcript from the YouTube page: which of the video's
// captions are taken, the wait for the player's token, and when to give up.
// The page here is a stand-in that answers the two questions the real page
// script answers, and its clock only moves when the fetcher pauses.

import { test } from 'node:test';
import assert from 'node:assert/strict';

import { createTranscriptFetcher } from '../src/extension/youtube-captions.js';

const talk = { id: 'youtube:iG9CE55wbtY', title: 'Do schools kill creativity?', channel: 'TED' };

/** Captions as YouTube sends them, saying `text`: per word when auto-generated, as one cue when the uploader's. */
function captionsSaying(text, { auto }) {
  const words = text.split(' ').map((word, i) => (i ? { utf8: ` ${word}`, tOffsetMs: i * 300 } : { utf8: word }));
  return JSON.stringify({ events: [{ tStartMs: 1000, dDurationMs: 4000, segs: auto ? words : [{ utf8: text }] }] });
}
const uploader = (language, more = {}) => ({ language, auto: false, hasToken: true, body: captionsSaying(`from the uploader in ${language}`, { auto: false }), ...more });
const autoGenerated = (language, more = {}) => ({ language, auto: true, hasToken: true, body: captionsSaying(`auto-generated in ${language}`, { auto: true }), ...more });

function standInPage({ video = talk.id, captions = [], advert = false } = {}) {
  let ms = 0;
  let later = [];
  const page = {
    video,
    captions,
    advert,
    silent: false, // true: the page gives no answer, as when its player has not caught up
    asked: [],
    /** Seconds since the fetcher started. */
    get seconds() {
      return ms / 1000;
    },
    /** Something that happens to the page at a time, as `page.at(40, () => …)`. */
    at(seconds, change) {
      later.push({ ms: seconds * 1000, change });
    },
    now: () => ms,
    pause: async (wait) => {
      ms += wait;
      if (ms > 3600_000) throw new Error('The fetcher is still waiting after an hour.');
      const due = later.filter((each) => each.ms <= ms);
      later = later.filter((each) => each.ms > ms);
      due.forEach((each) => each.change());
    },
    ask: async (message) => {
      page.asked.push(message.type);
      if (message.type === 'which-captions') {
        if (page.silent) return null;
        return { video: page.video, advert: page.advert, captions: page.captions.map(({ language, auto, hasToken, shownByDefault = false }) => ({ language, auto, hasToken, shownByDefault })) };
      }
      const wanted = page.captions[message.index];
      // Without the player's token YouTube answers with nothing.
      return message.video === page.video && wanted ? { status: 200, body: wanted.hasToken ? wanted.body : '' } : null;
    },
  };
  return page;
}
const fetcherOn = (page) => createTranscriptFetcher({ askPage: page.ask, pause: page.pause, now: page.now });

test("the video's captions are fetched from the page and come back as a Transcript", async () => {
  const page = standInPage({ captions: [autoGenerated('en')] });

  const transcript = await fetcherOn(page)(talk);

  assert.deepEqual(transcript, {
    language: 'en',
    source: 'auto-generated',
    timing: 'word',
    pieces: [
      { text: 'auto-generated', start: 1 },
      { text: ' in', start: 1.3 },
      { text: ' en', start: 1.6 },
    ],
  });
});

const taken = async (captions) => {
  const { language, source, timing } = await fetcherOn(standInPage({ captions }))(talk);
  return { language, source, timing };
};

test("the uploader's captions are taken when they are in the language the video is spoken in", async () => {
  // A video's one set of auto-generated captions is in the spoken language, so it says which that is.
  const captions = [uploader('af'), uploader('en'), uploader('fr'), autoGenerated('en')];

  assert.deepEqual(await taken(captions), { language: 'en', source: 'uploader', timing: 'cue' });
});

test('otherwise the auto-generated captions are taken', async () => {
  assert.deepEqual(await taken([autoGenerated('en')]), { language: 'en', source: 'auto-generated', timing: 'word' });
  assert.deepEqual(await taken([uploader('fr'), uploader('es'), autoGenerated('en')]), { language: 'en', source: 'auto-generated', timing: 'word' });
});

test("the uploader's captions in a regional form of the spoken language count as that language", async () => {
  assert.deepEqual(await taken([uploader('fr'), uploader('en-GB'), autoGenerated('en')]), { language: 'en-GB', source: 'uploader', timing: 'cue' });
  // The exact language is taken before a regional form of it.
  assert.deepEqual(await taken([uploader('pt-BR'), uploader('pt-PT'), autoGenerated('pt-PT')]), { language: 'pt-PT', source: 'uploader', timing: 'cue' });
});

test("with no auto-generated captions to name the spoken language, the uploader's captions the player shows by default are taken, or else the first", async () => {
  assert.deepEqual(await taken([uploader('af'), uploader('en', { shownByDefault: true })]), { language: 'en', source: 'uploader', timing: 'cue' });
  assert.deepEqual(await taken([uploader('af'), uploader('en')]), { language: 'af', source: 'uploader', timing: 'cue' });
});

test('a video dubbed into other languages has auto-generated captions for each, and the ones the player shows by default name the spoken language', async () => {
  // The list YouTube gives for youtube:u4Sy19aHhN0 (2026-10-07), a video spoken in English
  // with nineteen dubbed audio tracks: twenty auto-generated captions, Bangla listed first.
  const listed = ['bn', 'nl-NL', 'en', 'fr', 'de', 'iw', 'hi', 'id', 'it', 'ja', 'ko', 'ml', 'pl', 'pt', 'pa', 'ru', 'es', 'ta', 'te', 'uk'];
  const dubbed = listed.map((language) => autoGenerated(language, { shownByDefault: language === 'en' }));

  assert.deepEqual(await taken(dubbed), { language: 'en', source: 'auto-generated', timing: 'word' });
  // The uploader's captions in that language are still taken before the auto-generated ones.
  assert.deepEqual(await taken([uploader('en'), ...dubbed]), { language: 'en', source: 'uploader', timing: 'cue' });
});

test("on a dubbed video whose uploader gave captions, those are what the player shows by default, and they name the spoken language", async () => {
  // The list YouTube gives for youtube:HTlf3KNNez0 (2026-10-07), spoken in English with twenty
  // dubbed audio tracks: twenty-one auto-generated captions, Arabic first, and the uploader's English.
  const listed = ['ar', 'bn', 'nl-NL', 'en', '.en-US', 'fr-FR', 'de-DE', 'iw', 'hi', 'id', 'it', 'ja', 'ko', 'ml', 'pl', 'pt-BR', 'pa', 'ru', 'es-US', 'ta', 'te', 'uk'];
  const dubbed = listed.map((each) => (each.startsWith('.') ? uploader(each.slice(1), { shownByDefault: true }) : autoGenerated(each)));

  assert.deepEqual(await taken(dubbed), { language: 'en-US', source: 'uploader', timing: 'cue' });
});

test('a video with no captions has no Transcript, and nothing is fetched', async () => {
  const page = standInPage({ captions: [] });

  assert.equal(await fetcherOn(page)(talk), null);
  assert.deepEqual(page.asked, ['which-captions']);
});

test("the captions are fetched only once the player's token has arrived, however long that takes within the limit", async () => {
  const page = standInPage({ captions: [autoGenerated('en', { hasToken: false })] });
  page.at(40, () => (page.captions[0].hasToken = true)); // as the live check saw after a full page load

  const transcript = await fetcherOn(page)(talk);

  assert.equal(transcript.source, 'auto-generated');
  assert.equal(page.seconds, 40);
  assert.equal(page.asked.filter((type) => type === 'fetch-captions').length, 1, 'asked YouTube once, with the token');
});

test('after 90 s with no token the wait is over, and the fetch has failed', async () => {
  const page = standInPage({ captions: [autoGenerated('en', { hasToken: false })] });

  await assert.rejects(fetcherOn(page)(talk), /no token/);

  assert.equal(page.seconds, 90);
  assert.ok(!page.asked.includes('fetch-captions'), 'YouTube was never asked without the token');
});

test('a page that gives no answer yet is asked again, for no longer than the same 90 s', async () => {
  const slow = standInPage({ captions: [autoGenerated('en')] });
  slow.silent = true; // its player has not caught up with the address
  slow.at(3, () => (slow.silent = false));
  assert.equal((await fetcherOn(slow)(talk)).source, 'auto-generated');
  assert.equal(slow.seconds, 3);

  const dead = standInPage({ captions: [autoGenerated('en')] });
  dead.silent = true;
  await assert.rejects(fetcherOn(dead)(talk), /no token/);
  assert.equal(dead.seconds, 90);
});

test('while an advert plays the 90 s do not run', async () => {
  const page = standInPage({ captions: [autoGenerated('en', { hasToken: false })], advert: true });
  page.at(200, () => (page.advert = false));
  page.at(201, () => (page.captions[0].hasToken = true));
  assert.equal((await fetcherOn(page)(talk)).source, 'auto-generated');
  assert.equal(page.seconds, 201);

  const never = standInPage({ captions: [autoGenerated('en', { hasToken: false })], advert: true });
  never.at(200, () => (never.advert = false));
  await assert.rejects(fetcherOn(never)(talk), /no token/);
  assert.ok(never.seconds >= 289.5 && never.seconds <= 290, `gave up 90 s after the advert ended, at ${never.seconds} s`);
});

test('when YouTube answers the token with nothing, the fetch has failed, and it is not asked again', async () => {
  // What YouTube sends a browser it does not trust: 200, and an empty body.
  const page = standInPage({ captions: [autoGenerated('en', { body: '' })] });

  await assert.rejects(fetcherOn(page)(talk), /answered with nothing/);
  assert.deepEqual(page.asked, ['which-captions', 'fetch-captions']);
});

test('when the page has moved to another video, the fetch for this one stops', async () => {
  const page = standInPage({ video: 'youtube:rddfPNBNAJs', captions: [autoGenerated('en')] });

  await assert.rejects(fetcherOn(page)(talk), /another video/);
  assert.deepEqual(page.asked, ['which-captions']);
});
