// YouTube's captions become a Transcript before the core sees them. These
// tests give the captions as YouTube sends them (the lines below are from the
// live check's record) and read the Transcript that comes out.

import { test } from 'node:test';
import assert from 'node:assert/strict';

import { transcriptFromCaptions } from '../src/extension/youtube-captions.js';

const autoGenerated = JSON.stringify({
  wireMagic: 'pb3',
  events: [
    { tStartMs: 0, dDurationMs: 1638600, id: 1, wpWinPosId: 1, wsWinStyleId: 1 },
    { tStartMs: 654, dDurationMs: 1426, wWinId: 1, segs: [{ utf8: '[applause]' }] },
    { tStartMs: 790, dDurationMs: 1290, wWinId: 1, aAppend: 1, segs: [{ utf8: '\n' }] },
    { tStartMs: 800, dDurationMs: 2800, wWinId: 1, segs: [{ utf8: '>> Thank', isSpeakerChange: 1 }, { utf8: ' you.', tOffsetMs: 160 }] },
  ],
});

test('auto-generated captions become a word-timed Transcript, each piece with its own time', () => {
  assert.deepEqual(transcriptFromCaptions(autoGenerated, { language: 'en', auto: true }), {
    language: 'en',
    source: 'auto-generated',
    timing: 'word',
    pieces: [
      { text: '[applause]', start: 0.654 },
      { text: '>> Thank', start: 0.8, newSpeaker: true },
      { text: ' you.', start: 0.96 },
    ],
  });
});

const fromTheUploader = JSON.stringify({
  wireMagic: 'pb3',
  events: [
    { tStartMs: 27103, dDurationMs: 2575, segs: [{ utf8: 'Good morning. How are you?' }] },
    { tStartMs: 29702, dDurationMs: 1403, segs: [{ utf8: '(Audience) Good.' }] },
    { tStartMs: 31129, dDurationMs: 1668, segs: [{ utf8: "It's been great, hasn't it?" }] },
  ],
});

test("the uploader's captions become a cue-timed Transcript, each cue one piece with a start and an end", () => {
  assert.deepEqual(transcriptFromCaptions(fromTheUploader, { language: 'en', auto: false }), {
    language: 'en',
    source: 'uploader',
    timing: 'cue',
    pieces: [
      { text: 'Good morning. How are you?', start: 27.103, end: 29.678 },
      { text: '(Audience) Good.', start: 29.702, end: 31.105 },
      { text: "It's been great, hasn't it?", start: 31.129, end: 32.797 },
    ],
  });
});

test('the pieces come out in the order they are spoken, whatever order the captions list them in', () => {
  const outOfOrder = JSON.stringify({
    events: [
      { tStartMs: 2080, dDurationMs: 3320, segs: [{ utf8: 'Thank' }, { utf8: ' you.', tOffsetMs: 320 }] },
      { tStartMs: 800, dDurationMs: 2800, segs: [{ utf8: 'Good' }, { utf8: ' evening.', tOffsetMs: 160 }] },
    ],
  });

  assert.deepEqual(
    transcriptFromCaptions(outOfOrder, { language: 'en', auto: true }).pieces.map((piece) => [piece.start, piece.text]),
    [[0.8, 'Good'], [0.96, ' evening.'], [2.08, 'Thank'], [2.4, ' you.']]
  );
});
